// Behavioral API documentation mixin.
//
// Exposes exactly one public method, getApiDoc, which returns a static Markdown
// document describing the backend's current public API surface. The document is
// authored from the current source and reads no runtime state. It is a mixin
// (never a method on main.mo) and takes no parameters.
//
// NOTE: The Markdown is built in a local `let` inside the function body and
// returned directly. It is never bound to a top-level `let` inside this mixin —
// every top-level binding in a mixin is stable state and would trap at runtime.

mixin () {
  /// Return a Markdown document describing the backend's public API.
  public query func getApiDoc() : async Text {
    let doc : Text =
      "# Fantasy Football Auction — Backend API\n"
      # "\nThis document describes the public API of the Best Ball fantasy football auction backend. "
      # "It is generated from the current backend source and is accurate as of the build that produced it.\n"
      # "\n## Purpose\n"
      # "\nThe backend manages fantasy football auction rooms: room creation and membership, player "
      # "import, nominations, proxy bidding, chat, ADP datasets, bye-week mappings, admin recovery, "
      # "push notifications, RSS news aggregation, and Best Ball weekly lineup and cumulative "
      # "standings computation. Best Ball rooms are distinguished by the room's `gameType` "
      # "discriminator (`#BestBall`), which is chosen at room creation via `createRoom`'s "
      # "`gameType` parameter.\n"
      # "\n## Authentication and authorization\n"
      # "\nThe backend uses Internet Identity principals as user identifiers (`UserId = Principal`). "
      # "There is no username/password login; a caller is identified by the principal of the "
      # "authenticated session that signs each request. Anonymous callers (the `aaaaa-aa` principal) "
      # "are treated as unauthenticated and are rejected or given empty results by guarded methods.\n"
      # "\n### Registration prerequisite\n"
      # "\nRegistration happens implicitly when a caller signs in through the app's own frontend and "
      # "first calls `setDisplayName` (or `setAvatarUrl`), which creates a `UserProfile` keyed by the "
      # "caller's principal. The **first** caller to register becomes the global admin (the "
      # "`adminPrincipalStore` \"admin\" entry is set once and never overwritten). A caller who never "
      # "signed in through the frontend is unregistered even if they belong to the app's owner, and a "
      # "signed-in caller derived against a different origin is a different principal than the one the "
      # "frontend registered. A direct API caller must therefore call `setDisplayName` once as a "
      # "signed-in caller before any role-guarded call (guarded queries included).\n"
      # "\n### Identity derivation\n"
      # "\nThe app's frontend pins an Internet Identity derivation origin, published at "
      # "`/.well-known/ii-derivation-origin` when available. An agent already holding the user's "
      # "Internet Identity authorization derives the correct per-app principal against that origin, "
      # "for example `icp identity link web <name> --app <host>`. Such a delegation acts with the "
      # "user's full authority in this app until it expires.\n"
      # "\n### Roles\n"
      # "\n- **Anonymous**: the `aaaaa-aa` principal. Treated as unauthenticated; guarded methods reject "
      # "it or return empty/zeroed results.\n"
      # "- **Global admin**: the registered admin principal (first `setDisplayName` caller) or a "
      # "hardcoded admin principal. Gates player import, ADP import, room deletion, key management, "
      # "notification diagnostics, RSS configuration, and participant identity "
      # "transfer. May also call `syncWeeklyStats` for any room (see below).\n"
      # "- **Room admin (host)**: the `room.admin` principal of a specific room. Gates room lifecycle "
      # "transitions, settings updates, participant removal, and Best Ball configuration.\n"
      # "- **Room participant**: any principal in `room.participants`. Gates room-scoped actions "
      # "(nominate, bid, chat, ready, lineup/standings reads) and, for a room whose "
      # "`room.season == season`, may call `syncWeeklyStats` for that room's season/week.\n"
      # "\n## Units and encodings\n"
      # "\n- `RoomId = Text` (a decimal string from a monotonic counter).\n"
      # "- `UserId = Principal`.\n"
      # "- `NominationId = Nat` (monotonic, never shrinks).\n"
      # "- `Timestamp = Int` — nanoseconds from `Time.now()` (not seconds).\n"
      # "- `season` and `week` are `Nat`. The season is the room's canonical NFL season "
      # "(`Room.season`, set at creation); weeks are 1-based NFL weeks. Never hardcode a year.\n"
      # "- Fantasy points are `Float`. Weekly stats yardage fields (`passYds`, `rushYds`, `recYds`) are "
      # "`Int` because negative yardage is valid; all other stat fields are `Nat`.\n"
      # "- `ScoringFormat` is a variant: `#std`, `#halfPpr`, `#ppr`, or `#custom(CustomScoringSettings)`.\n"
      # "- `AuctionState`: `#Waiting`, `#Active`, `#Paused`, `#Completed`.\n"
      # "- `NominationState`: `#Active`, `#Closed`, `#Expired`.\n"
      # "- `BidHistoryEventType`: `#nominationCreated`, `#leaderChanged`, `#nominationEnded`.\n"
      # "\n## Best Ball read APIs (Phase 4)\n"
      # "\nBoth methods are read-only queries that consume the Phase 3 optimal lineup calculator "
      # "(`calculateOptimalWeeklyLineup`) as the single source of truth. No lineup optimization or "
      # "scoring logic is duplicated. They never mutate stable state.\n"
      # "\n### `getWeeklyLineup(roomId, participantId, week) -> { #ok : WeeklyLineupView; #err : Text }`\n"
      # "\nReturns one participant's optimal Best Ball lineup for one week. `WeeklyLineupView` contains "
      # "`roomId`, `participantId`, `displayName`, `week`, `starters` (array of `LineupSlot`), `bench` "
      # "(array of `LineupBenchEntry`), and `total` (Float).\n"
      # "\n- **Access**: the caller must be a participant of the room (`AuctionLib.isParticipant`). "
      # "Non-participants cannot inspect private-room data; the method is not global-admin-only.\n"
      # "- **Best Ball only**: a room whose `gameType != #BestBall` returns "
      # "`#err \"Room is not a Best Ball room\"`.\n"
      # "- **Unsynced week**: if no `WeeklyPlayerStats` record exists for any owned player in that "
      # "season+week, returns an empty lineup (`starters = []`, `bench = []`, `total = 0.0`) — not an "
      # "error.\n"
      # "- **Missing player stats**: a player with no stats record in an otherwise synced week "
      # "contributes 0 points but remains owned and may appear on the bench.\n"
      # "- Errors: `#err \"Room not found\"`, `#err \"Room is not a Best Ball room\"`, "
      # "`#err \"Not a participant in this room\"`, `#err \"Participant not found\"`.\n"
      # "\n### `getStandings(roomId) -> { #ok : [StandingsEntry]; #err : Text }`\n"
      # "\nComputes Cumulative Best Ball standings for a room. Each participant's cumulative score is the "
      # "sum of their optimal Best Ball weekly score across every applicable week from "
      # "`BestBallConfig.startWeek` through `FINAL_WEEK` (17, inclusive). `StandingsEntry` contains "
      # "`participantId`, `displayName`, and `totalPoints` (Float).\n"
      # "\n- **Cached finalized weeks**: for any week whose `SyncStatusRecord.status == #finalized`, the "
      # "participant's score is read from the `finalizedWeeklyScores` cache (written exactly once at "
      # "finalization, never recomputed). Only the single current non-finalized (live, `#partial`) week is "
      # "computed dynamically via the Phase 3 calculator. This keeps `getStandings` at "
      # "\"cached lookups + one live computation\" cost — the optimizer never runs for finalized weeks.\n"
      # "- **Access**: the caller must be a participant of the room.\n"
      # "- **Best Ball only**: a room whose `gameType != #BestBall` returns "
      # "`#err \"Room is not a Best Ball room\"`.\n"
      # "- **Unsynced weeks** contribute 0 points and do not fail the calculation.\n"
      # "- **Missing player stats** contribute 0 while the player stays owned/benched.\n"
      # "- **Deterministic ordering**: descending by `totalPoints`, with equal scores broken by the "
      # "stable participant identifier ascending (`Principal.compare`). Ordering never depends on map "
      # "iteration order.\n"
      # "- Errors: `#err \"Room not found\"`, `#err \"Room is not a Best Ball room\"`, "
      # "`#err \"Not a participant in this room\"`, `#err \"No participants\"`.\n"
      # "\n### `getWeeklyStandings(roomId, week) -> { #ok : [StandingsEntry]; #err : Text }`\n"
      # "\nComputes single-week Best Ball standings for a room. Each participant's score for the "
      # "requested `week` is their optimal Best Ball weekly score for that week alone. It reuses the "
      # "same `StandingsEntry` result type as `getStandings` "
      # "(`participantId`, `displayName`, `totalPoints` Float) — there is no separate single-week "
      # "result type.\n"
      # "\n- **Cached finalized weeks**: for a `week` whose `SyncStatusRecord.status == #finalized`, "
      # "each participant's score is read from the `finalizedWeeklyScores` cache (never recomputed). "
      # "Only the single live (`#partial`) week is computed dynamically via the Phase 3 calculator.\n"
      # "- **Access**: identical to `getStandings` — the caller must be a participant of the room, "
      # "and a room whose `gameType != #BestBall` returns `#err \"Room is not a Best Ball room\"`.\n"
      # "- **Week-boundary validation**: the requested `week` must satisfy "
      # "`BestBallConfig.startWeek <= week <= FINAL_WEEK` (17). A `week` below `startWeek` or "
      # "above `FINAL_WEEK` is rejected with `#err` — this is the backend enforcement of the navigation "
      # "boundary, not merely a frontend nicety.\n"
      # "- **Unsynced week**: a fully unsynced week (no `WeeklyPlayerStats` record for any owned "
      # "player in that season+week) returns a valid all-zero, deterministically-ordered list — "
      # "treated as 0 points for each participant, not an error. This is consistent with how "
      # "`getStandings` already treats unsynced weeks within its sum.\n"
      # "- **Missing player stats**: a player with no stats record in an otherwise synced week "
      # "contributes 0 points while staying owned/benched, without erroring.\n"
      # "- **Deterministic ordering**: identical to `getStandings` — descending by `totalPoints`, "
      # "with equal scores broken by the stable participant identifier ascending "
      # "(`Principal.compare`). Ordering never depends on map iteration order.\n"
      # "- **Shared helpers**: `getWeeklyStandings` shares the same room lookup, `gameType` check, "
      # "`BestBallConfig` lookup, participant-access gating, and sort comparator as `getStandings` "
      # "(extracted into shared internal helpers). The only difference is the scoring loop: "
      # "`getStandings` sums across `startWeek..FINAL_WEEK`, while `getWeeklyStandings` scores the "
      # "single requested `week`.\n"
      # "- Errors: `#err \"Room not found\"`, `#err \"Room is not a Best Ball room\"`, "
      # "`#err \"Not a participant in this room\"`, `#err \"No participants\"`, and the "
      # "week-boundary `#err` for out-of-range weeks.\n"
      # "\n## Head-to-Head standings (Phase 12a)\n"
      # "\nFor a `#BestBall` + `#HeadToHead` room, the regular-season schedule is **derived**, never "
      # "stored. After `endAuction` completes, the schedule is completely determined by the "
      # "immutable `room.participants`, the immutable `BestBallConfig.startWeek`, the immutable "
      # "`competitionMode`/`playoffTeams`, and the `FINAL_WEEK` constant (17). There is no second "
      # "source of truth and no persisted schedule, bracket, or standings state. Weekly matchups "
      # "come from a standard round-robin circle method over the participants sorted by "
      # "`Principal.compare`; when the regular season spans more than one full cycle, the "
      # "additional weeks repeat the exact same deterministic pairings in the same round order.\n"
      # "\n### `getH2HStandings(roomId) -> { #ok : [H2HStandingEntry]; #err : Text }`\n"
      # "\nComputes Head-to-Head regular-season standings for a room. Each team's weekly result is "
      # "resolved via the derived pairing table for weeks in `startWeek..regularSeasonEnd`. "
      # "`H2HStandingEntry` contains `participant` (the team's owner principal), `displayName`, "
      # "`wins`, `losses`, `ties`, `pointsFor` (Float, the team's cumulative optimal weekly score "
      # "across its regular-season games), and `gamesPlayed` (the count of resolved, synced weeks).\n"
      # "\n- **Cached finalized weeks**: for any week whose `SyncStatusRecord.status == #finalized`, "
      # "each team's weekly score is read from the `finalizedWeeklyScores` cache (never recomputed). "
      # "Only the single live (`#partial`) week is computed dynamically via the Phase 3 calculator. "
      # "The same caching invariant as `getStandings` applies — finalized weeks never run the "
      # "optimizer.\n"
      # "\n- **Access**: the caller must be a participant of the room (`AuctionLib.isParticipant`). "
      # "Non-participants cannot inspect private-room data.\n"
      # "- **Best Ball + Head-to-Head only**: a room that is not `#BestBall` + `#HeadToHead` is "
      # "rejected with `#err`.\n"
      # "- **Unsynced week**: a week with no synced stats produces no result for that week — it is "
      # "not counted in `gamesPlayed` and contributes no points.\n"
      # "- **Ties**: genuine ties are allowed and recorded; there is no synthetic tiebreaker.\n"
      # "- **Playoff weeks out of scope**: weeks in `playoffStartWeek..FINAL_WEEK` (when "
      # "`playoffTeams > 0`) are not resolved this phase; `getH2HStandings` reflects only "
      # "regular-season results.\n"
      # "- **Deterministic ordering**: wins descending, `pointsFor` descending, then "
      # "`Principal.compare` ascending — never map iteration order.\n"
      # "- Errors: `#err \"Room not found\"`, `#err \"Room is not a Best Ball room\"`, "
      # "`#err \"Not a participant in this room\"`, `#err \"No participants\"`.\n"
      # "\n`getStandings` and `getWeeklyStandings` reject `#HeadToHead` rooms with `#err` — "
      # "cumulative standings apply only to `#Cumulative` rooms.\n"
      # "\n## Playoff bracket (Phase 12b)\n"
      # "\nFor a `#BestBall` + `#HeadToHead` room with `playoffTeams > 0`, the playoff bracket is "
      # "**derived, never stored**. The bracket, every game, and the champion are pure computations "
      # "over already-persisted data — there is no persisted bracket, game, or champion state. The "
      # "champion is the recursively-resolved winner of the final game, computed on demand.\n"
      # "\n### `getPlayoffBracket(roomId) -> { #ok : PlayoffBracketResult; #err : Text }`\n"
      # "\nDerives and resolves the fixed-slot playoff bracket for a `#HeadToHead` room with "
      # "`playoffTeams > 0`. `PlayoffBracketResult` contains `games` (an array of `PlayoffGameResult`) "
      # "and `champion` (`#some : ResolvedContestant` once the final game resolves, or `#inProgress` "
      # "otherwise). Each `PlayoffGameResult` carries the fixed `game` (its `home`/`away` slots and "
      # "`week`), the state of each slot (`home`/`away`), and the game's `status`.\n"
      # "\n- **Access**: the caller must be a participant of the room (`AuctionLib.isParticipant`). "
      # "Non-participants cannot inspect private-room data.\n"
      # "- **Best Ball + Head-to-Head with playoffs only**: a room that is not `#BestBall` + "
      # "`#HeadToHead` is rejected with `#err \"Room is not a Head-to-Head Best Ball room\"`. A "
      # "`#Cumulative` room is rejected with the distinct `#err \"Room is a Cumulative room; playoffs "
      # "require a Head-to-Head room\"`. An H2H room with `playoffTeams == 0` is rejected with the "
      # "distinct `#err \"Room has no playoffs (playoffTeams is 0)\"`.\n"
      # "- **Seeding**: comes from `getH2HStandings`' existing deterministic ordering (wins → "
      # "pointsFor → `Principal.compare`), restricted to the top `playoffTeams` entries. Bracket seed "
      # "numbers are **1-based**: `#Seed n` resolves to the participant occupying seed `n` in that "
      # "ordering, i.e. standings array index `n - 1`.\n"
      # "- **Fixed-slot brackets** (no reseeding after rounds): 4-team (semis Seed1vSeed4 and "
      # "Seed2vSeed3 in `playoffStartWeek`, championship in `playoffStartWeek + 1`); 6-team (round 1 "
      # "Seed3vSeed6 and Seed4vSeed5 in `playoffStartWeek`, semifinals Seed1vwinner(1) and "
      # "Seed2vwinner(0) in `playoffStartWeek + 1` — Seeds 1-2 occupy their semifinal slot directly, "
      # "no game — championship in `playoffStartWeek + 2`); 8-team (quarterfinals Seed1v8, Seed4v5, "
      # "Seed3v6, Seed2v7 in `playoffStartWeek`, semifinals in `playoffStartWeek + 1`, championship in "
      # "`playoffStartWeek + 2`). Week assignments fall out of the existing `playoffStartWeek`/"
      # "`playoffRounds` derivation — never a separately computed value.\n"
      # "- **Slot states** (`BracketSlotState`): `#resolved : ResolvedContestant` (a seed slot always "
      # "resolves immediately, independent of any week's sync status; a winner-of slot resolves only "
      # "when both its slots are resolved and its week is settled), `#pendingOnSync` (both underlying "
      # "slots known but the week not yet settled — \"not yet played\", never a score of 0), and "
      # "`#pendingOnDependency` (at least one underlying slot is still an unresolved `#WinnerOf`). "
      # "`ResolvedContestant = { participant; seed; score }` carries each contestant's **original "
      # "seed** forward through the bracket.\n"
      # "- **Game status** (`GameStatus`): `#resolved : { homeScore; awayScore; winner }` when both "
      # "slots are known and the week is settled — reports both actual scores and the winner; higher "
      # "score wins. On an **exact tie**, the contestant with the numerically lower (better) original "
      # "seed advances — never a scoring tiebreaker, never an error. `#pendingOnSync` when both slots "
      # "are known but the week is not yet settled. `#pendingOnDependency` when at least one slot is "
      # "still an unresolved `#WinnerOf`.\n"
      # "- **Champion**: the winner of the final game once it resolves, or `#inProgress` otherwise. "
      # "Never stored — computed on demand.\n"
      # "- **Lifecycle/polling**: a game resolves only when its week is finalized (its "
      # "`SyncStatusRecord.status == #finalized`, per `SyncStatusLib.isWeekFinalized`). Poll `getPlayoffBracket` "
      # "after each week's stats are synced and finalized; a game that was `#pendingOnSync` becomes `#resolved` once "
      # "its week is finalized, and a `#pendingOnDependency` game resolves once its upstream games "
      # "resolve. There is no manual seeding override and no commissioner control — the bracket is "
      # "read-only.\n"
      # "- **Errors**: `#err \"Room not found\"`, `#err \"Room is not a Head-to-Head Best Ball room\"`, "
      # "`#err \"Room is a Cumulative room; playoffs require a Head-to-Head room\"`, "
      # "`#err \"Room has no playoffs (playoffTeams is 0)\"`, `#err \"Not a participant in this room\"`, "
      # "`#err \"Room is not a Best Ball room\"`, `#err \"No participants\"`.\n"
      # "\n## Room and membership\n"
      # "\n- `createRoom(gameType, competitionMode, playoffTeams, name, startingBudget, settings, isPublic, "
      # "password, playerFilter, maxRosterSize, rosterSettings, teamCount, leagueFormat, season, "
      # "scoringFormat) -> { #ok : RoomId; #err : Text }` — creates a room and makes the caller its "
      # "admin and first participant. `gameType` is required and must be `#Auction` or `#BestBall`; "
      # "`#Guillotine` is rejected with `#err \"Guillotine is not yet implemented\"`. Requires a "
      # "non-empty name, a positive budget, and a password for private rooms.\n"
      # "\n`competitionMode : CompetitionMode` (`#Cumulative` | `#HeadToHead`) and "
      # "`playoffTeams : Nat` are set once at creation and immutable forever after. They are "
      # "irrelevant for `#Auction` rooms (accepted and ignored). For `#BestBall` rooms the four "
      # "valid configuration families are enforced together at creation:\n"
      # "\n1. **Auction** — `competitionMode`/`playoffTeams` irrelevant.\n"
      # "2. **Best Ball / Cumulative** — `playoffTeams` must be `0`.\n"
      # "3. **Best Ball / Head-to-Head without playoffs** — `playoffTeams` must be `0`.\n"
      # "4. **Best Ball / Head-to-Head with playoffs** — `playoffTeams` must be exactly `4`, `6`, "
      # "or `8`.\n"
      # "\nAny other combination is rejected with a clear `#err` at creation time.\n"
      # "- `joinRoom(roomId, password) -> { #ok : (); #err : Text }` — join a room in `#Waiting` state "
      # "under the participant limit.\n"
      # "- `leaveRoom(roomId) -> { #ok : (); #err : Text }` — leave a room (admin cannot leave).\n"
      # "- `getUserRooms() -> [RoomSummary]` — update (self-healing) returning rooms the caller is a "
      # "participant of.\n"
      # "- `reconcileMembershipIndexes() -> ()` — one-time repair entry point (not for end users).\n"
      # "- `removeUserFromRoom(roomId, userId) -> { #ok : (); #err : Text }` — room-admin only.\n"
      # "- `transferParticipantIdentity(roomId, oldPrincipal, newPrincipal) -> { #ok : Text; #err : Text }` "
      # "— global-admin only; moves a participant's slot to a new principal.\n"
      # "- `getRoomState(roomId) -> { #ok : RoomView; #err : Text }` — full room view including the "
      # "caller's own proxy bids and drafted player IDs.\n"
      # "- `getRooms() -> [RoomSummary]` — global-admin only; non-admins receive an empty array.\n"
      # "- `listPublicRooms() -> [RoomSummary]` — public rooms only, no auth.\n"
      # "- `joinPrivateRoomByPassword(password) -> { #ok : RoomId; #err : Text }` — matches a private "
      # "room by password; returns a single generic error on failure so private rooms cannot be "
      # "enumerated.\n"
      # "- `deleteRoom(roomId) -> { #ok : (); #err : Text }` — global-admin only. Refused if a "
      # "`BestBallConfig` exists for the room (Best Ball data protection).\n"
      # "\n## Auction lifecycle\n"
      # "\n- `startAuction(roomId)`, `pauseAuction(roomId)`, `resumeAuction(roomId)`, "
      # "`endAuction(roomId, startWeek)` — room-admin only; transition the room state and "
      # "freeze/resume timers. `endAuction` takes an optional `startWeek : ?Nat` whose meaning "
      # "depends on the room's `gameType`: for an `#Auction` room `startWeek` must be `null` (a "
      # "provided value is rejected with `#err`); for a `#BestBall` room `startWeek` is required "
      # "and must satisfy `1 <= startWeek <= 17` (rejected otherwise), and on success the "
      # "`BestBallConfig { startWeek }` is written atomically with the completion. All validation "
      # "happens before any state mutation, so a rejected call leaves the room in its prior "
      # "pre-completion state.\n"
      # "\nFor a `#BestBall` + `#HeadToHead` room with playoffs (`playoffTeams > 0`), `endAuction` "
      # "adds two further validations: `playoffTeams` must not exceed the room's participant count, "
      # "and there must be enough weeks for a full regular season before the playoffs begin — "
      # "`regularSeasonEnd(playoffTeams) - startWeek + 1` must be at least "
      # "`numberOfRounds(participantCount)`, otherwise the call is rejected with "
      # "`#err \"Not enough weeks for a full regular season before playoffs begin\"`. These checks "
      # "do not apply to `#Cumulative` rooms or `#HeadToHead` rooms without playoffs, whose only "
      # "constraint remains `1 <= startWeek <= 17`.\n"
      # "- `updateRoomSettings(roomId, nomTimerSecs, bidTimerSecs, maxRosterSize, adpDataset) -> "
      # "{ #ok : (); #err : Text }` — room-admin only; allowed in `#Waiting`/`#Paused`, or `#Active` "
      # "with no active nominations.\n"
      # "- `toggleReady(roomId)`, `setSkipNominationTurn(roomId, skip)`, `setParticipantPaid(roomId, "
      # "targetUserId, paid)` — participant/host toggles.\n"
      # "- `setNominationOrder(roomId, orderedUsers)`, `setActiveNominationCount(roomId, count)`, "
      # "`randomizeNominationOrder(roomId)` — room-admin only; `#Waiting`/`#Paused` only.\n"
      # "- `editParticipantBudget(roomId, targetUser, newBudget)`, `removeParticipant(roomId, "
      # "targetUser)` — room-admin only.\n"
      # "\n## Nominations and bidding\n"
      # "\n- `nominatePlayer(roomId, playerId) -> { #ok : NominationId; #err : Text }` — participant "
      # "only; enforces turn ownership, budget, roster cap, active-nomination limit, and "
      # "already-nominated/drafted checks.\n"
      # "- `getNominations(roomId) -> [NominationView]` — no auth.\n"
      # "- `sweepNominations(roomId) -> ()` — public update that resolves expired nomination timers.\n"
      # "- `setNominationQueue(roomId, playerId)`, `clearNominationQueue(roomId)`, "
      # "`getNominationQueue(roomId) -> ?Text` — participant-only auto-nomination queue.\n"
      # "- `placeProxyBid(nominationId, roomId, maxBid) -> { #ok : (); #err : Text }` — participant "
      # "only; the only bidding entry point. `maxBid` is private; only the visible bid is public.\n"
      # "- `getNominationHistory(nominationId) -> [BidHistoryEvent]` — no auth; oldest-first events.\n"
      # "\n## Players and ADP\n"
      # "\n- `getPlayers(queryText, position) -> [Player]`, `getPlayersByRoom(roomId, queryText, "
      # "positionFilter) -> [Player]` — no auth; the latter enforces the room's player filter.\n"
      # "- `importPlayers(batch) -> { #ok : Nat; #err : Text }` — global-admin only; upserts players "
      # "and resolves `byeWeek` from the backend bye-week store.\n"
      # "- `clearPlayers() -> { #ok : (); #err : Text }` — global-admin only.\n"
      # "- `importADPDataset(entries, datasetType)`, `removeADPDataset(datasetType)` — global-admin "
      # "only; keyed by \"all\" or \"rookies\".\n"
      # "- `getADPDataset()`, `getActiveADPDataset()`, `getADPDatasetByType(datasetType)`, "
      # "`getPlayersWithADP()` — no auth.\n"
      # "\n## Chat\n"
      # "\n- `sendMessage(roomId, message) -> { #ok : (); #err : Text }` — participant only; triggers "
      # "@mention notifications.\n"
      # "- `getMessages(roomId, limit) -> [ChatMessage]` — no auth; newest-first.\n"
      # "- `toggleMessageReaction(roomId, messageId, emoji) -> { #ok : (); #err : Text }` — participant "
      # "only.\n"
      # "\n## Weekly stats and Best Ball configuration\n"
      # "\n- `syncWeeklyStats(roomId, season, week, batch) -> { #ok : Nat; #err : Text }` — "
      # "upserts raw weekly player stats keyed by `playerId|season|week`. The backend does not fetch "
      # "stats itself; the frontend sends a typed batch. The per-player upsert is safe for repeated "
      # "writes — re-syncing a week cleanly overwrites (no duplicates). After processing, the "
      # "`(season, week)` is marked `#partial` (the mutable, non-terminal active state) whenever any "
      # "stats are recorded, regardless of how many owned players have actually played yet — "
      # "`stored == 0` mid-progress does NOT imply \"nothing happened\" and never locks or "
      # "misrepresents the week. A week only becomes terminal via the finalization operation, never "
      # "via a sync call. **Authorization**: the caller must be the global admin OR a participant of "
      # "the room identified by `roomId` whose `room.season == season`. If `roomId` does not resolve "
      # "to a room, or the caller is neither the global admin nor a participant of that room, the "
      # "call is rejected with a clear `#err` before any state is written. **Finalization guard**: "
      # "if the target `(season, week)` is already `#finalized`, the call is rejected with "
      # "`#err \"Week {week} of {season} is finalized and cannot be resynced\"` before any state is "
      # "written. A `#notYetAttempted` or `#partial` week is unaffected and remains retry-eligible. "
       # "**Cooldown no-op**: a live/partial week synced again within the server-side cooldown window "
       # "returns a harmless no-op success (no duplicate writes, no error) rather than re-processing "
       # "the batch. **Per-entry validation**: each entry is validated conservatively before storage — "
       # "negative yardage, touchdown/interception/fumble/reception counts above generous bounds derived "
       # "from real NFL single-game records, a non-numeric or empty `playerId`, a `week` outside 1-18, or "
       # "a `season` outside 2000-2100 causes that single entry to be skipped (counted in the same "
       # "`skipped` diagnostic as season/week mismatches), never the whole call. Legitimate zero-stat "
       # "entries and statistically unusual but possible performances (e.g. a record game) still validate "
       # "and store. This is not a provenance check — the backend cannot verify the data came from "
       # "Sleeper.\n"
      # "- `getPlayerWeeklyPoints(playerId, season, week, format) -> ?Float` — no auth; returns null "
      # "when no stats entry exists (distinguishing no-data from a real zero).\n"
      # "- `getBestBallConfig(roomId) -> ?BestBallConfig` — no auth; null when Best Ball is not "
      # "enabled. The config carries only `startWeek`; the season always ends at the module-level "
      # "`FINAL_WEEK` constant (17).\n"
      # "\n## Weekly sync status and automatic finalization\n"
      # "\nThe backend tracks a per-`(season, week)` sync status record for Best Ball weekly stats. "
      # "This is **visibility, not full autonomy**: the backend never fetches from Sleeper and never "
      # "makes an HTTPS outcall. The actual fetch+parse+submit happens in an authenticated admin's "
      # "browser session; these methods only record and expose what is missing.\n"
      # "\n### Week sync-status lifecycle\n"
      # "\nEach `(season, week)` moves through a three-state lifecycle:\n"
      # "\n- `#notYetAttempted` — the starting state; never attempted.\n"
      # "- `#partial` — the mutable, **non-terminal** active/partial state. A week is marked `#partial` "
      # "whenever a sync attempt records any stats for it, regardless of how many owned players have "
      # "actually played yet. A partial sync where most owned players legitimately haven't played yet "
      # "stays `#partial` (retry-eligible, non-terminal) — `stored == 0` mid-progress does NOT imply "
      # "\"nothing happened\" and never locks or misrepresents the week. A `#partial` week may receive "
      # "repeated `syncWeeklyStats` calls without being locked.\n"
      # "- `#finalized` — **terminal**. Once set, `syncWeeklyStats` rejects further writes for that "
      # "`(season, week)`. A week only becomes terminal via the finalization operation — never via a "
      # "sync call, regardless of how many players have data.\n"
      # "\n`SyncStatusRecord` fields: `season` (Nat), `week` (Nat), `lastAttemptedAt` (Int, "
      # "nanoseconds from `Time.now()`), `status` (`#notYetAttempted | #partial | #finalized`), "
      # "`lastError` (`?Text`), `lastSuccessfulAt` (`?Int`, nanoseconds).\n"
      # "\n### Automatic finalization trigger\n"
      # "\nFinalization is **automatic** — normal operation never depends on a human. The trigger is "
      # "the synchronization flow itself: whenever a new week is synced, `finalizePriorPartialWeeks` "
      # "finalizes every earlier `#partial` week in the same season (weeks below the just-synced week). "
      # "This is reliable because a week is provably complete the moment a subsequent week is synced — "
      # "its games ended before the later week's games began. A once-per-day recurring timer acts as a "
      # "backstop, re-enforcing the same invariant (finalizing every `#partial` week below the live "
      # "week) and backfilling the cache for pre-existing `#finalized` weeks. This guarantees **at most "
      # "one non-finalized (live) week per season**, so multiple completed-but-unfinalized weeks can "
      # "never accumulate and push `getStandings` over the 5B query instruction ceiling.\n"
      # "\n### Finalized-weekly-score cache\n"
      # "\nAt the moment a week finalizes, each participant's final optimal weekly-lineup total is "
      # "computed and written **exactly once** into the `finalizedWeeklyScores` cache (keyed by "
      # "`roomId|season|week|principal`). It is never recomputed or overwritten afterward. "
      # "`getStandings`, `getWeeklyStandings`, and `getH2HStandings` read the cached value for any "
      # "`#finalized` week; only the single current non-finalized (live, `#partial`) week is computed "
      # "dynamically via `calculateOptimalWeeklyLineup`. The live week is never written to the cache "
      # "and is always recomputed on each query — no invalidation logic is needed for it.\n"
      # "\n- `computeDedupSeasonWeeks() -> [(Nat, Nat)]` — global-admin only; returns the deduplicated "
      # "set of `(season, week)` pairs across all `#BestBall` rooms' `startWeek..FINAL_WEEK` ranges, "
      # "unions overlapping ranges across rooms on the same season. Non-admins receive an empty array.\n"
      # "- `getSyncStatusRecords() -> [SyncStatusRecord]` — global-admin only; returns every status "
      # "record for the admin status view. Non-admins receive an empty array.\n"
      # "- `getFlaggedWeeks() -> [SyncStatusRecord]` — global-admin only; returns the weeks eligible "
      # "for a partial sync. It flags only the single live (`#partial`) week — weeks that haven't "
      # "started yet (`#notYetAttempted`) are excluded, so the Admin Panel's auto-sync only targets "
      # "weeks that are actually in progress. It is an **update** (not a query) because it also "
      # "ensures a status record exists for every tracked week, creating a `#notYetAttempted` record "
      # "when none exists yet. Non-admins receive an empty array.\n"
      # "- `recordSyncStatus(season, week, status, lastError, lastSuccessfulAt) -> "
      # "{ #ok : SyncStatusRecord; #err : Text }` — global-admin only; records/updates the status for "
      # "a `(season, week)`. The atomic duplicate-sync guard lives here: if the week is already "
      # "`#finalized`, the submission is rejected with `#err \"Already synced\"` and cannot reprocess or "
      # "replace the terminal state. `#notYetAttempted` and `#partial` are retry-eligible and may be "
      # "overwritten. Non-admins receive `#err \"Only the admin can record sync status\"`.\n"
      # "\nA once-per-day recurring timer computes the deduplicated `(season, week)` set, re-enforces "
      # "the finalization invariant (finalizing every `#partial` week below the live week), backfills "
      # "the cache for pre-existing `#finalized` weeks, and flags the live week for partial sync. It "
      # "never fetches from Sleeper and never makes an outcall. The timer is re-registered in the "
      # "post-upgrade hook because `mo:core/Timer` timers are not persisted across canister upgrades.\n"
      # "\n### Host-only recovery endpoints\n"
      # "\nNormal operation is fully automatic; the following exist ONLY as recovery mechanisms and "
      # "are not required for normal use:\n"
      # "\n- `finalizeWeek(season, week) -> { #ok : Nat; #err : Text }` — global-admin only; manually "
      # "finalizes a `#partial` week and writes its cache. Refused (`#err \"Week already finalized\"`) "
      # "for a `#finalized` week and (`#err \"Week not in a partial state\"`) for a `#notYetAttempted` "
      # "week. Non-admins receive `#err \"Only the admin can finalize a week\"`.\n"
      # "- `backfillFinalizedScores() -> Nat` — global-admin only; populates the cache for every "
      # "`#finalized` week lacking a cache entry (the post-migration population for pre-existing "
      # "`#synced`→`#finalized` weeks). Idempotent — only fills missing entries, never overwrites. "
      # "Non-admins receive `0`.\n"
      # "\n## Settled and final weeks\n"
      # "\nA `(season, week)` is **finalized** iff its `SyncStatusRecord.status == #finalized`. "
      # "`#notYetAttempted` and `#partial` are **not** finalized; a `#partial` week remains "
      # "retry-eligible and is the single live week. A Best Ball season (a room) is **final** when it "
      # "is `#BestBall`, has a `BestBallConfig`, and every week from `startWeek` to `FINAL_WEEK` (17) "
      # "is finalized. This is purely computed, never persisted.\n"
      # "\n- `syncWeeklyStats` rejects a resync of a finalized `(season, week)` with "
      # "`#err \"Week {week} of {season} is finalized and cannot be resynced\"`.\n"
      # "- Finalization applies only to rooms where `gameType == #BestBall` and a `BestBallConfig` "
      # "exists. Pure Auction rooms, completed-but-not-converted rooms, and (later) Guillotine rooms "
      # "are entirely unaffected.\n"
      # "\n## Admin recovery\n"
      # "\n- `setRecoveryPassword(newSecret) -> Result<(), Text>` — global-admin only; requires a secret "
      # "of at least 16 characters; stores a SHA-256 hash.\n"
      # "- `recoverAdmin(providedSecret) -> Result<(), Text>` — anyone; reassigns the global admin on "
      # "a correct password. Failed attempts apply an escalating lockout (2^(attempts-5) minutes, "
      # "capped at 24 hours) after 5 failures.\n"
      # "\n## Bye weeks\n"
      # "\n- `setByeWeeks(mapping) -> { #ok : (); #err : Text }` — global-admin only; replaces the "
      # "bye-week mapping and re-applies it to imported players. Validates each team is non-empty and "
      # "each bye week is 1–18.\n"
      # "- `getByeWeeks() -> [(Text, Nat)]` — no auth; returns the default 2025 mapping if none "
      # "imported.\n"
      # "\n## Notifications and RSS\n"
      # "\n- `setGiphyApiKey(key)`, `setOneSignalApiKey(key)` — global-admin only.\n"
      # "- `getGiphyApiKey() -> ?Text` — any authenticated (non-anonymous) caller.\n"
      # "- `getOneSignalApiKey() -> ?Text` — global-admin only.\n"
      # "- `setOneSignalPlayerId(id) -> ()` — any authenticated caller stores their own player ID.\n"
      # "- `getOneSignalPlayerIds() -> [(Text, Text)]` — global-admin only.\n"
      # "- `sendTestPush() -> { #ok : { body; playerId; looksSuccessful }; #err : Text }` — global-admin "
      # "only; sends a test push to the caller's own player ID.\n"
      # "- `getNotificationCounters()`, `getHeartbeatDiagnostics()`, "
      # "`getNotificationQueueSnapshot()`, `getRoomParticipantPrincipals(roomId)` — global-admin only; "
      # "non-admins receive zeroed/empty results.\n"
      # "- `adminDrainQueueNow() -> { #ok : Nat; #err : Text }` — global-admin only.\n"
      # "- `setRssFeedUrls(urls)`, `setRssRefreshIntervalSecs(seconds)` — global-admin only.\n"
      # "- `getRssFeedUrls() -> [Text]`, `getRssRefreshIntervalSecs() -> Nat`, "
      # "`getLastRssFetchStatus() -> [(Text, Bool)]` — any authenticated caller; anonymous callers get "
      # "empty/default values.\n"
      # "- `fetchRssFeeds() -> Text` — public update that fetches and caches RSS content.\n"
      # "- `transform(raw) -> TransformationOutput` — HTTP outcall transformation callback.\n"
      # "\n## Identity and profile\n"
      # "\n- `getDisplayName(userId) -> ?Text`, `setDisplayName(name)`, `setAvatarUrl(url)`, "
      # "`getProfile() -> UserProfile`, `checkIsAdmin() -> Bool`.\n"
      # "\n## Lifecycle and polling\n"
      # "\nAuction timers are resolved by `sweepExpiredNominations`, which is triggered automatically "
      # "inside most auction update methods and by the public `sweepNominations(roomId)` call. The "
      # "frontend should call `sweepNominations` (or any auction update) to drive timer resolution "
      # "rather than relying on a background timer. Best Ball weekly stats are synced explicitly via "
      # "`syncWeeklyStats`; there is no automatic weekly stat synchronization. Finalization, however, "
      # "**is** automatic: syncing a new week triggers `finalizePriorPartialWeeks`, which finalizes "
      # "every earlier `#partial` week in the same season, and a once-per-day timer acts as a backstop "
      # "(finalizing every `#partial` week below the live week and backfilling the cache). The actual "
      # "stat sync still requires an authenticated admin's browser session; the Admin Panel's auto-sync "
      # "polls `getFlaggedWeeks` (which flags only the live `#partial` week) on a minimum-time-since-"
      # "last-sync interval (~5 minutes) so the same trigger can safely run repeatedly while the panel "
      # "remains open.\n"
      # "\n## Mutation retry safety and idempotency\n"
      # "\n- `syncWeeklyStats` is an upsert keyed by `playerId|season|week`; re-syncing a `#notYetAttempted` "
      # "or `#partial` week cleanly overwrites (no duplicates). A `#finalized` `(season, week)` is "
      # "rejected up front with the finalized-week error before any state is written. A live/partial "
      # "week synced again within the server-side cooldown window returns a harmless no-op success "
      # "(no duplicate writes, no error) rather than re-processing the batch.\n"
      # "- `recordSyncStatus` enforces the atomic duplicate-sync guard: a `(season, week)` already "
      # "`#finalized` rejects later submissions with `#err \"Already synced\"`; `#notYetAttempted` and "
      # "`#partial` are retry-eligible and may be overwritten.\n"
      # "- `finalizeWeek` (host-only recovery) is idempotent: a `#finalized` week is refused with "
      # "`#err \"Week already finalized\"` and never re-finalized; the cache write is exactly-once "
      # "(an existing cache entry is never overwritten).\n"
      # "- `backfillFinalizedScores` (host-only recovery) is idempotent — it only fills missing cache "
      # "entries, never overwrites.\n"
      # "- `importPlayers` and `importADPDataset` are upserts; re-importing overwrites.\n"
      # "- `setDisplayName`/`setAvatarUrl` overwrite the caller's profile.\n"
      # "- `endAuction` writes the `BestBallConfig { startWeek }` atomically with the completion "
      # "for a `#BestBall` room; a rejected call (invalid `startWeek`) leaves the room in its "
      # "prior pre-completion state. The former `setBestBallConfig`/`convertRoomToBestBall` "
      # "methods were removed entirely.\n"
      # "- `setByeWeeks` replaces the mapping atomically.\n"
      # "- `toggleReady`/`toggleMessageReaction` are idempotent toggles.\n"
      # "- `finalizeNomination` (internal) is guarded so a duplicate close is a no-op.\n"
      # "- `deleteRoom` is destructive and global-admin only; it is refused for Best Ball rooms.\n"
      # "\n## Errors, traps, and limits\n"
      # "\n- Most guarded methods return `#err` with a `Text` message rather than trapping, so callers "
      # "can branch on the outcome.\n"
      # "- `getWeeklyLineup`/`getStandings`/`getWeeklyStandings` return `#err` for non-Best-Ball rooms "
      # "and non-participants; unsynced weeks are not errors. `getWeeklyStandings` additionally "
      # "rejects out-of-range weeks with `#err`. `getH2HStandings` returns `#err` for rooms that "
      # "are not `#BestBall` + `#HeadToHead` and for non-participants; unsynced weeks simply "
      # "produce no result for that week. `getPlayoffBracket` returns `#err` for rooms that "
      # "are not `#BestBall` + `#HeadToHead`, for `#Cumulative` rooms, for H2H rooms with "
      # "`playoffTeams == 0`, and for non-participants; unresolved games are reported as "
      # "`#pendingOnSync`/`#pendingOnDependency`, never as a score of 0.\n"
      # "- Chat is capped at 500 messages per room (oldest evicted); system messages are deduplicated "
      # "within 120 seconds.\n"
      # "- The notification queue is capped at 1000 entries (oldest evicted); titles are capped at 50 "
      # "chars and bodies at 100 chars.\n"
      # "- ADP datasets are capped at 2000 entries.\n"
      # "- `recoverAdmin` applies an escalating lockout after 5 failed attempts.\n"
      # "- `getRooms` returns an empty array to non-admins so private-room metadata is never leaked.\n"
      # "- `getOneSignalApiKey` and `getOneSignalPlayerIds` return null/empty to non-admins.\n"
      # "\n## Non-obvious integration gotchas\n"
      # "\n- `Timestamp` is nanoseconds, not seconds; convert before display.\n"
      # "- `getUserRooms` is an **update** (not a query) because it self-heals the membership index.\n"
      # "- `getFlaggedWeeks` is an **update** (not a query) because it ensures a status record exists "
      # "for every tracked week before returning the live-week set eligible for partial sync.\n"
      # "- `getMessages` returns newest-first; stored messages are oldest-first.\n"
      # "- `getPlayerWeeklyPoints` returns `null` for no-data and `0.0` for a real zero-point "
      # "performance — do not conflate them.\n"
      # "- Best Ball rooms are identified by the room's `gameType == #BestBall` discriminator, "
      # "which is chosen at room creation via `createRoom`'s `gameType` parameter. The "
      # "`BestBallConfig { startWeek }` is written by `endAuction` atomically with the room's "
      # "completion; the season always runs from `startWeek` through the `FINAL_WEEK` constant "
      # "(17). There is no stored end week and no separate conversion step.\n"
      # "- `getStandings` reads finalized weeks from the `finalizedWeeklyScores` cache and computes "
      # "only the single live (`#partial`) week dynamically; each (participant, live-week) pair is "
      # "calculated exactly once. The optimizer never runs for finalized weeks.\n"
      # "- `getWeeklyStandings` shares its room lookup, access gating, and sort comparator with "
      # "`getStandings` via extracted internal helpers, so the two methods' access rules and "
      # "ordering are guaranteed identical. It enforces the week boundary server-side: a `week` "
      # "outside `startWeek..FINAL_WEEK` is rejected with `#err`, so callers should bound "
      # "navigation to that range rather than relying on the error alone.\n"
      # "- The H2H regular-season schedule is **derived, not stored** — it is recomputed on demand "
      # "from immutable room inputs (`participants`, `startWeek`, `competitionMode`/`playoffTeams`, "
      # "`FINAL_WEEK`). No operation can alter it after `endAuction` completes, and there is no "
      # "persisted schedule or standings state to keep in sync.\n"
      # "- `getH2HStandings` only resolves regular-season weeks (`startWeek..regularSeasonEnd`). "
      # "Playoff weeks (`playoffStartWeek..FINAL_WEEK`, when `playoffTeams > 0`) are out of scope "
      # "this phase and are not reflected in the returned standings.\n"
      # "- `getPlayoffBracket` is read-only and derives everything on demand — there is no persisted "
      # "bracket, game, or champion state, and no manual seeding override or commissioner control. "
      # "Bracket seeds are 1-based (`#Seed n` = standings index `n - 1`); a game resolves only when "
      # "its week is settled, and a `#pendingOnSync` game must not be shown as a score of 0.\n"
      # "- `getStandings`/`getWeeklyStandings` (cumulative) reject `#HeadToHead` rooms with `#err`, "
      # "and `getH2HStandings` rejects non-`#BestBall`/non-`#HeadToHead` rooms — the two standings "
      # "views are mutually exclusive by `competitionMode`.\n"
      # "- The global admin is assigned on first `setDisplayName`; a caller who never registered via "
      # "the frontend is unregistered even if they belong to the app's owner.\n"
      # "- A delegation derived against a different origin is a different principal than the one the "
      # "frontend registered, so it will not match room membership or admin checks.\n"
      # "\n## OQL data intelligence\n"
      # "\nThe backend exposes its persisted collections as queryable entities via the Caffeine Data "
      # "Intelligence agent (`schema()` and `execute()`). Room-scoped tables are controller-only; "
      # "per-user tables (`profile`, `userRoom`) are controller-or-scoped and owned by `userId`. "
      # "The `syncStatus` table exposes the per-`(season, week)` sync status records (controller-only, "
      # "admin diagnostic data); its `status` column is the `SyncStatus` variant collapsed to a Text "
      # "tag (`notYetAttempted` | `partial` | `finalized`), and `lastError`/`lastSuccessfulAt` "
      # "use empty-string/zero sentinels for absent values. The `finalizedWeeklyScore` table exposes "
      # "the finalized-weekly-score cache (controller-only, room-scoped): one row per participant per "
      # "`#finalized` week, with `roomId`, `season`, `week`, `principal`, and the cached `score` "
      # "(Float). The Head-to-Head feature adds **no** new "
      # "persisted data — the regular-season schedule and standings are derived on demand from "
      # "immutable room inputs, so no new OQL entity is required for them.\n";
    doc;
  };
};
