/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomId = IDL.Text;
export const GameType = IDL.Variant({
  'BestBall' : IDL.Null,
  'Guillotine' : IDL.Null,
  'Auction' : IDL.Null,
});
export const CompetitionMode = IDL.Variant({
  'Cumulative' : IDL.Null,
  'HeadToHead' : IDL.Null,
});
export const AuctionSettings = IDL.Record({
  'minBidIncrement' : IDL.Nat,
  'maxActivePicks' : IDL.Nat,
  'adpDataset' : IDL.Text,
  'nomTimerSecs' : IDL.Nat,
  'maxParticipants' : IDL.Nat,
  'bidTimerSecs' : IDL.Nat,
  'maxRosterSize' : IDL.Opt(IDL.Nat),
});
export const PlayerFilter = IDL.Record({
  'filterType' : IDL.Text,
  'positions' : IDL.Vec(IDL.Text),
});
export const RosterSettings = IDL.Record({
  'qb' : IDL.Nat,
  'rb' : IDL.Nat,
  'te' : IDL.Nat,
  'wr' : IDL.Nat,
  'flex' : IDL.Nat,
  'superflex' : IDL.Nat,
  'superflexPositions' : IDL.Vec(IDL.Text),
  'bench' : IDL.Nat,
  'flexPositions' : IDL.Vec(IDL.Text),
});
export const CustomScoringSettings = IDL.Record({
  'recTdPoints' : IDL.Float64,
  'passYdPoints' : IDL.Float64,
  'intPoints' : IDL.Float64,
  'recYdPoints' : IDL.Float64,
  'twoPtPoints' : IDL.Float64,
  'rushTdPoints' : IDL.Float64,
  'rushYdPoints' : IDL.Float64,
  'fumbleLostPoints' : IDL.Float64,
  'passTdPoints' : IDL.Float64,
  'receptionPoints' : IDL.Float64,
});
export const ScoringFormat = IDL.Variant({
  'ppr' : IDL.Null,
  'std' : IDL.Null,
  'halfPpr' : IDL.Null,
  'custom' : CustomScoringSettings,
});
export const UserId = IDL.Principal;
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const FinalizeResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const AdpEntry = IDL.Record({
  'adp' : IDL.Float64,
  'name' : IDL.Text,
  'team' : IDL.Opt(IDL.Text),
  'position' : IDL.Opt(IDL.Text),
});
export const ADPDataset = IDL.Record({
  'lastUpdated' : IDL.Int,
  'importedAt' : IDL.Int,
  'entries' : IDL.Vec(AdpEntry),
});
export const BestBallConfig = IDL.Record({ 'startWeek' : IDL.Nat });
export const SyncStatus = IDL.Variant({
  'finalized' : IDL.Null,
  'notYetAttempted' : IDL.Null,
  'partial' : IDL.Null,
});
export const SyncStatusRecord = IDL.Record({
  'status' : SyncStatus,
  'lastAttemptedAt' : IDL.Int,
  'week' : IDL.Nat,
  'season' : IDL.Nat,
  'lastError' : IDL.Opt(IDL.Text),
  'lastSuccessfulAt' : IDL.Opt(IDL.Int),
});
export const H2HStandingEntry = IDL.Record({
  'displayName' : IDL.Text,
  'gamesPlayed' : IDL.Nat,
  'pointsFor' : IDL.Float64,
  'ties' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'participant' : UserId,
});
export const Timestamp = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'displayName' : IDL.Text,
  'userId' : UserId,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserId))),
});
export const NominationId = IDL.Nat;
export const BidHistoryEventType = IDL.Variant({
  'nominationEnded' : IDL.Null,
  'leaderChanged' : IDL.Null,
  'nominationCreated' : IDL.Null,
});
export const BidHistoryEvent = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : UserId,
  'isAutoBid' : IDL.Opt(IDL.Bool),
  'timestamp' : Timestamp,
  'playerName' : IDL.Text,
  'amount' : IDL.Nat,
  'eventType' : BidHistoryEventType,
});
export const NominationState = IDL.Variant({
  'Closed' : IDL.Null,
  'Active' : IDL.Null,
  'Expired' : IDL.Null,
});
export const NominationView = IDL.Record({
  'id' : NominationId,
  'bidLeader' : IDL.Opt(UserId),
  'playerId' : IDL.Text,
  'team' : IDL.Text,
  'bidLeaderName' : IDL.Opt(IDL.Text),
  'timerSecsRemaining' : IDL.Nat,
  'state' : NominationState,
  'imageUrl' : IDL.Opt(IDL.Text),
  'playerName' : IDL.Text,
  'nominatedBy' : UserId,
  'currentBid' : IDL.Nat,
  'roomId' : RoomId,
  'position' : IDL.Text,
});
export const Player = IDL.Record({
  'id' : IDL.Text,
  'adp' : IDL.Float64,
  'yearsExp' : IDL.Nat,
  'name' : IDL.Text,
  'team' : IDL.Text,
  'byeWeek' : IDL.Opt(IDL.Nat),
  'position' : IDL.Text,
  'headshotUrl' : IDL.Opt(IDL.Text),
});
export const GameStatus = IDL.Variant({
  'resolved' : IDL.Record({
    'winner' : UserId,
    'homeScore' : IDL.Float64,
    'awayScore' : IDL.Float64,
  }),
  'pendingOnDependency' : IDL.Null,
  'pendingOnSync' : IDL.Null,
});
export const ResolvedContestant = IDL.Record({
  'seed' : IDL.Nat,
  'score' : IDL.Float64,
  'participant' : UserId,
});
export const BracketSlotState = IDL.Variant({
  'resolved' : ResolvedContestant,
  'pendingOnDependency' : IDL.Null,
  'pendingOnSync' : IDL.Null,
});
export const BracketSlot = IDL.Variant({
  'WinnerOf' : IDL.Nat,
  'Seed' : IDL.Nat,
});
export const PlayoffGame = IDL.Record({
  'away' : BracketSlot,
  'home' : BracketSlot,
  'week' : IDL.Nat,
});
export const PlayoffGameResult = IDL.Record({
  'status' : GameStatus,
  'away' : BracketSlotState,
  'game' : PlayoffGame,
  'home' : BracketSlotState,
});
export const PlayoffBracketResult = IDL.Record({
  'games' : IDL.Vec(PlayoffGameResult),
  'champion' : IDL.Variant({
    'some' : ResolvedContestant,
    'inProgress' : IDL.Null,
  }),
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : UserId,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const PublicParticipantBudget = IDL.Record({
  'publicAvailableBudget' : IDL.Nat,
  'totalBudget' : IDL.Nat,
  'spentBudget' : IDL.Nat,
});
export const PrivateParticipantBudget = IDL.Record({
  'availableBudget' : IDL.Nat,
  'committedBudget' : IDL.Nat,
  'totalBudget' : IDL.Nat,
  'spentBudget' : IDL.Nat,
});
export const ParticipantBudgetView = IDL.Variant({
  'public' : PublicParticipantBudget,
  'private' : PrivateParticipantBudget,
});
export const WonPlayer = IDL.Record({
  'playerId' : IDL.Text,
  'team' : IDL.Text,
  'closedAt' : Timestamp,
  'playerName' : IDL.Text,
  'byeWeek' : IDL.Opt(IDL.Nat),
  'nominatedBy' : UserId,
  'position' : IDL.Text,
  'winningBid' : IDL.Nat,
});
export const ParticipantView = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : UserId,
  'budgetView' : ParticipantBudgetView,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'skipNominationTurn' : IDL.Bool,
  'wonPlayers' : IDL.Vec(WonPlayer),
});
export const AuctionState = IDL.Variant({
  'Paused' : IDL.Null,
  'Active' : IDL.Null,
  'Waiting' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Room = IDL.Record({
  'id' : RoomId,
  'leagueFormat' : IDL.Opt(IDL.Text),
  'rosterSettings' : IDL.Opt(RosterSettings),
  'participants' : IDL.Vec(UserId),
  'admin' : UserId,
  'nominatorIndex' : IDL.Nat,
  'readyParticipants' : IDL.Vec(UserId),
  'password' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'scoringFormat' : ScoringFormat,
  'startingBudget' : IDL.Nat,
  'teamCount' : IDL.Opt(IDL.Nat),
  'season' : IDL.Nat,
  'nominationTurnPausedAt' : IDL.Opt(Timestamp),
  'playoffTeams' : IDL.Nat,
  'playerFilter' : PlayerFilter,
  'state' : AuctionState,
  'paidParticipants' : IDL.Vec(UserId),
  'settings' : AuctionSettings,
  'gameType' : GameType,
  'isPublic' : IDL.Bool,
  'competitionMode' : CompetitionMode,
  'nominationTurnStartedAt' : Timestamp,
});
export const ProxyBid = IDL.Record({
  'userId' : UserId,
  'maxBid' : IDL.Nat,
  'nominationId' : NominationId,
});
export const RoomView = IDL.Record({
  'queuedPlayerId' : IDL.Opt(IDL.Text),
  'participants' : IDL.Vec(ParticipantView),
  'draftedPlayerIds' : IDL.Vec(IDL.Text),
  'currentNominatorName' : IDL.Opt(IDL.Text),
  'currentNominatorId' : IDL.Opt(UserId),
  'room' : Room,
  'nominationTimerSecsRemaining' : IDL.Nat,
  'activeNominations' : IDL.Vec(NominationView),
  'completedNominations' : IDL.Vec(NominationView),
  'myProxyBids' : IDL.Vec(ProxyBid),
});
export const RoomSummary = IDL.Record({
  'id' : RoomId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'state' : AuctionState,
  'participantCount' : IDL.Nat,
  'maxParticipants' : IDL.Nat,
  'isPublic' : IDL.Bool,
  'adminId' : UserId,
});
export const StandingsEntry = IDL.Record({
  'displayName' : IDL.Text,
  'participantId' : UserId,
  'totalPoints' : IDL.Float64,
});
export const LineupSlot = IDL.Record({
  'playerId' : IDL.Opt(IDL.Text),
  'slot' : IDL.Text,
  'position' : IDL.Text,
  'points' : IDL.Float64,
});
export const LineupBenchEntry = IDL.Record({
  'playerId' : IDL.Text,
  'points' : IDL.Float64,
});
export const WeeklyLineupView = IDL.Record({
  'total' : IDL.Float64,
  'displayName' : IDL.Text,
  'starters' : IDL.Vec(LineupSlot),
  'week' : IDL.Nat,
  'participantId' : UserId,
  'bench' : IDL.Vec(LineupBenchEntry),
  'roomId' : RoomId,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const WeeklyPlayerStats = IDL.Record({
  'twoPtConversions' : IDL.Nat,
  'receptions' : IDL.Nat,
  'ints' : IDL.Nat,
  'fumblesLost' : IDL.Nat,
  'playerId' : IDL.Text,
  'week' : IDL.Nat,
  'season' : IDL.Nat,
  'passTds' : IDL.Nat,
  'passYds' : IDL.Int,
  'rushTds' : IDL.Nat,
  'rushYds' : IDL.Int,
  'recTds' : IDL.Nat,
  'recYds' : IDL.Int,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  'adminDrainQueueNow' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'backfillFinalizedScores' : IDL.Func([], [IDL.Nat], []),
  'checkIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'clearNominationQueue' : IDL.Func([RoomId], [], []),
  'clearPlayers' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'computeDedupSeasonWeeks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [],
    ),
  'createRoom' : IDL.Func(
      [
        GameType,
        CompetitionMode,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        AuctionSettings,
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Opt(PlayerFilter),
        IDL.Opt(IDL.Nat),
        IDL.Opt(RosterSettings),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Nat,
        ScoringFormat,
      ],
      [IDL.Variant({ 'ok' : RoomId, 'err' : IDL.Text })],
      [],
    ),
  'deleteRoom' : IDL.Func(
      [RoomId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'editParticipantBudget' : IDL.Func(
      [RoomId, UserId, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'endAuction' : IDL.Func(
      [RoomId, IDL.Opt(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'fetchRssFeeds' : IDL.Func([], [IDL.Text], []),
  'finalizeWeek' : IDL.Func([IDL.Nat, IDL.Nat], [FinalizeResult], []),
  'getADPDataset' : IDL.Func([], [IDL.Opt(ADPDataset)], ['query']),
  'getADPDatasetByType' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ADPDataset)],
      ['query'],
    ),
  'getActiveADPDataset' : IDL.Func([], [IDL.Opt(ADPDataset)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getBestBallConfig' : IDL.Func(
      [RoomId],
      [IDL.Opt(BestBallConfig)],
      ['query'],
    ),
  'getByeWeeks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getCycleBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getDisplayName' : IDL.Func([UserId], [IDL.Opt(IDL.Text)], ['query']),
  'getFlaggedWeeks' : IDL.Func([], [IDL.Vec(SyncStatusRecord)], []),
  'getGiphyApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getH2HStandings' : IDL.Func(
      [RoomId],
      [IDL.Variant({ 'ok' : IDL.Vec(H2HStandingEntry), 'err' : IDL.Text })],
      ['query'],
    ),
  'getHeartbeatDiagnostics' : IDL.Func(
      [],
      [
        IDL.Record({
          'lastNotificationWorkerError' : IDL.Opt(IDL.Text),
          'lastNotificationWorkerCompletedAt' : IDL.Int,
          'lastNotificationWorkerStartedAt' : IDL.Int,
          'notificationWorkerEntryCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLastRssFetchStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [RoomId, IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getNominationHistory' : IDL.Func(
      [NominationId],
      [IDL.Vec(BidHistoryEvent)],
      ['query'],
    ),
  'getNominationQueue' : IDL.Func([RoomId], [IDL.Opt(IDL.Text)], ['query']),
  'getNominations' : IDL.Func([RoomId], [IDL.Vec(NominationView)], ['query']),
  'getNotificationCounters' : IDL.Func(
      [],
      [
        IDL.Record({
          'expired' : IDL.Nat,
          'sent' : IDL.Nat,
          'queued' : IDL.Nat,
          'processed' : IDL.Nat,
          'failed' : IDL.Nat,
          'retried' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getNotificationQueueSnapshot' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'title' : IDL.Text,
            'userId' : IDL.Text,
            'attempts' : IDL.Nat,
            'ageSeconds' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getOneSignalApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getOneSignalPlayerIds' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getPlayerWeeklyPoints' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, ScoringFormat],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getPlayers' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(Player)],
      ['query'],
    ),
  'getPlayersByRoom' : IDL.Func(
      [RoomId, IDL.Text, IDL.Text],
      [IDL.Vec(Player)],
      ['query'],
    ),
  'getPlayersWithADP' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getPlayoffBracket' : IDL.Func(
      [RoomId],
      [IDL.Variant({ 'ok' : PlayoffBracketResult, 'err' : IDL.Text })],
      [],
    ),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'getRoomParticipantPrincipals' : IDL.Func(
      [RoomId],
      [
        IDL.Variant({
          'ok' : IDL.Vec(
            IDL.Record({ 'principal' : IDL.Text, 'displayName' : IDL.Text })
          ),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getRoomState' : IDL.Func(
      [RoomId],
      [IDL.Variant({ 'ok' : RoomView, 'err' : IDL.Text })],
      ['query'],
    ),
  'getRooms' : IDL.Func([], [IDL.Vec(RoomSummary)], []),
  'getRssFeedUrls' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRssRefreshIntervalSecs' : IDL.Func([], [IDL.Nat], ['query']),
  'getStandings' : IDL.Func(
      [RoomId],
      [IDL.Variant({ 'ok' : IDL.Vec(StandingsEntry), 'err' : IDL.Text })],
      ['query'],
    ),
  'getSyncStatusRecords' : IDL.Func([], [IDL.Vec(SyncStatusRecord)], ['query']),
  'getUserRooms' : IDL.Func([], [IDL.Vec(RoomSummary)], []),
  'getWeeklyLineup' : IDL.Func(
      [RoomId, UserId, IDL.Nat],
      [IDL.Variant({ 'ok' : WeeklyLineupView, 'err' : IDL.Text })],
      ['query'],
    ),
  'getWeeklyStandings' : IDL.Func(
      [RoomId, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(StandingsEntry), 'err' : IDL.Text })],
      ['query'],
    ),
  'importADPDataset' : IDL.Func(
      [IDL.Vec(AdpEntry), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'importPlayers' : IDL.Func(
      [IDL.Vec(Player)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'joinPrivateRoomByPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : RoomId, 'err' : IDL.Text })],
      [],
    ),
  'joinRoom' : IDL.Func(
      [RoomId, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'leaveRoom' : IDL.Func(
      [RoomId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'listPublicRooms' : IDL.Func([], [IDL.Vec(RoomSummary)], ['query']),
  'nominatePlayer' : IDL.Func(
      [RoomId, IDL.Text],
      [IDL.Variant({ 'ok' : NominationId, 'err' : IDL.Text })],
      [],
    ),
  'pauseAuction' : IDL.Func(
      [RoomId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'placeProxyBid' : IDL.Func(
      [NominationId, RoomId, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'randomizeNominationOrder' : IDL.Func(
      [RoomId],
      [IDL.Variant({ 'ok' : IDL.Vec(UserId), 'err' : IDL.Text })],
      [],
    ),
  'reconcileMembershipIndexes' : IDL.Func([], [], []),
  'recordSyncStatus' : IDL.Func(
      [IDL.Nat, IDL.Nat, SyncStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
      [IDL.Variant({ 'ok' : SyncStatusRecord, 'err' : IDL.Text })],
      [],
    ),
  'recoverAdmin' : IDL.Func([IDL.Text], [Result], []),
  'removeADPDataset' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'removeParticipant' : IDL.Func(
      [RoomId, UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeUserFromRoom' : IDL.Func(
      [RoomId, UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resumeAuction' : IDL.Func(
      [RoomId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendMessage' : IDL.Func(
      [RoomId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'sendTestPush' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'body' : IDL.Text,
            'playerId' : IDL.Text,
            'looksSuccessful' : IDL.Bool,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'setActiveNominationCount' : IDL.Func(
      [RoomId, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setAvatarUrl' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setByeWeeks' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setDisplayName' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setGiphyApiKey' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setNominationOrder' : IDL.Func(
      [RoomId, IDL.Vec(UserId)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setNominationQueue' : IDL.Func(
      [RoomId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setOneSignalApiKey' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setOneSignalPlayerId' : IDL.Func([IDL.Text], [], []),
  'setParticipantPaid' : IDL.Func(
      [RoomId, UserId, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setRecoveryPassword' : IDL.Func([IDL.Text], [Result], []),
  'setRssFeedUrls' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setRssRefreshIntervalSecs' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setSkipNominationTurn' : IDL.Func(
      [RoomId, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'startAuction' : IDL.Func(
      [RoomId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'sweepNominations' : IDL.Func([RoomId], [], []),
  'syncWeeklyStats' : IDL.Func(
      [RoomId, IDL.Nat, IDL.Nat, IDL.Vec(WeeklyPlayerStats)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'toggleMessageReaction' : IDL.Func(
      [RoomId, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'toggleReady' : IDL.Func(
      [RoomId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'transferParticipantIdentity' : IDL.Func(
      [RoomId, UserId, UserId],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateRoomSettings' : IDL.Func(
      [RoomId, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomId = IDL.Text;
  const GameType = IDL.Variant({
    'BestBall' : IDL.Null,
    'Guillotine' : IDL.Null,
    'Auction' : IDL.Null,
  });
  const CompetitionMode = IDL.Variant({
    'Cumulative' : IDL.Null,
    'HeadToHead' : IDL.Null,
  });
  const AuctionSettings = IDL.Record({
    'minBidIncrement' : IDL.Nat,
    'maxActivePicks' : IDL.Nat,
    'adpDataset' : IDL.Text,
    'nomTimerSecs' : IDL.Nat,
    'maxParticipants' : IDL.Nat,
    'bidTimerSecs' : IDL.Nat,
    'maxRosterSize' : IDL.Opt(IDL.Nat),
  });
  const PlayerFilter = IDL.Record({
    'filterType' : IDL.Text,
    'positions' : IDL.Vec(IDL.Text),
  });
  const RosterSettings = IDL.Record({
    'qb' : IDL.Nat,
    'rb' : IDL.Nat,
    'te' : IDL.Nat,
    'wr' : IDL.Nat,
    'flex' : IDL.Nat,
    'superflex' : IDL.Nat,
    'superflexPositions' : IDL.Vec(IDL.Text),
    'bench' : IDL.Nat,
    'flexPositions' : IDL.Vec(IDL.Text),
  });
  const CustomScoringSettings = IDL.Record({
    'recTdPoints' : IDL.Float64,
    'passYdPoints' : IDL.Float64,
    'intPoints' : IDL.Float64,
    'recYdPoints' : IDL.Float64,
    'twoPtPoints' : IDL.Float64,
    'rushTdPoints' : IDL.Float64,
    'rushYdPoints' : IDL.Float64,
    'fumbleLostPoints' : IDL.Float64,
    'passTdPoints' : IDL.Float64,
    'receptionPoints' : IDL.Float64,
  });
  const ScoringFormat = IDL.Variant({
    'ppr' : IDL.Null,
    'std' : IDL.Null,
    'halfPpr' : IDL.Null,
    'custom' : CustomScoringSettings,
  });
  const UserId = IDL.Principal;
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const FinalizeResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const AdpEntry = IDL.Record({
    'adp' : IDL.Float64,
    'name' : IDL.Text,
    'team' : IDL.Opt(IDL.Text),
    'position' : IDL.Opt(IDL.Text),
  });
  const ADPDataset = IDL.Record({
    'lastUpdated' : IDL.Int,
    'importedAt' : IDL.Int,
    'entries' : IDL.Vec(AdpEntry),
  });
  const BestBallConfig = IDL.Record({ 'startWeek' : IDL.Nat });
  const SyncStatus = IDL.Variant({
    'finalized' : IDL.Null,
    'notYetAttempted' : IDL.Null,
    'partial' : IDL.Null,
  });
  const SyncStatusRecord = IDL.Record({
    'status' : SyncStatus,
    'lastAttemptedAt' : IDL.Int,
    'week' : IDL.Nat,
    'season' : IDL.Nat,
    'lastError' : IDL.Opt(IDL.Text),
    'lastSuccessfulAt' : IDL.Opt(IDL.Int),
  });
  const H2HStandingEntry = IDL.Record({
    'displayName' : IDL.Text,
    'gamesPlayed' : IDL.Nat,
    'pointsFor' : IDL.Float64,
    'ties' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'participant' : UserId,
  });
  const Timestamp = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'displayName' : IDL.Text,
    'userId' : UserId,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserId))),
  });
  const NominationId = IDL.Nat;
  const BidHistoryEventType = IDL.Variant({
    'nominationEnded' : IDL.Null,
    'leaderChanged' : IDL.Null,
    'nominationCreated' : IDL.Null,
  });
  const BidHistoryEvent = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : UserId,
    'isAutoBid' : IDL.Opt(IDL.Bool),
    'timestamp' : Timestamp,
    'playerName' : IDL.Text,
    'amount' : IDL.Nat,
    'eventType' : BidHistoryEventType,
  });
  const NominationState = IDL.Variant({
    'Closed' : IDL.Null,
    'Active' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const NominationView = IDL.Record({
    'id' : NominationId,
    'bidLeader' : IDL.Opt(UserId),
    'playerId' : IDL.Text,
    'team' : IDL.Text,
    'bidLeaderName' : IDL.Opt(IDL.Text),
    'timerSecsRemaining' : IDL.Nat,
    'state' : NominationState,
    'imageUrl' : IDL.Opt(IDL.Text),
    'playerName' : IDL.Text,
    'nominatedBy' : UserId,
    'currentBid' : IDL.Nat,
    'roomId' : RoomId,
    'position' : IDL.Text,
  });
  const Player = IDL.Record({
    'id' : IDL.Text,
    'adp' : IDL.Float64,
    'yearsExp' : IDL.Nat,
    'name' : IDL.Text,
    'team' : IDL.Text,
    'byeWeek' : IDL.Opt(IDL.Nat),
    'position' : IDL.Text,
    'headshotUrl' : IDL.Opt(IDL.Text),
  });
  const GameStatus = IDL.Variant({
    'resolved' : IDL.Record({
      'winner' : UserId,
      'homeScore' : IDL.Float64,
      'awayScore' : IDL.Float64,
    }),
    'pendingOnDependency' : IDL.Null,
    'pendingOnSync' : IDL.Null,
  });
  const ResolvedContestant = IDL.Record({
    'seed' : IDL.Nat,
    'score' : IDL.Float64,
    'participant' : UserId,
  });
  const BracketSlotState = IDL.Variant({
    'resolved' : ResolvedContestant,
    'pendingOnDependency' : IDL.Null,
    'pendingOnSync' : IDL.Null,
  });
  const BracketSlot = IDL.Variant({ 'WinnerOf' : IDL.Nat, 'Seed' : IDL.Nat });
  const PlayoffGame = IDL.Record({
    'away' : BracketSlot,
    'home' : BracketSlot,
    'week' : IDL.Nat,
  });
  const PlayoffGameResult = IDL.Record({
    'status' : GameStatus,
    'away' : BracketSlotState,
    'game' : PlayoffGame,
    'home' : BracketSlotState,
  });
  const PlayoffBracketResult = IDL.Record({
    'games' : IDL.Vec(PlayoffGameResult),
    'champion' : IDL.Variant({
      'some' : ResolvedContestant,
      'inProgress' : IDL.Null,
    }),
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : UserId,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const PublicParticipantBudget = IDL.Record({
    'publicAvailableBudget' : IDL.Nat,
    'totalBudget' : IDL.Nat,
    'spentBudget' : IDL.Nat,
  });
  const PrivateParticipantBudget = IDL.Record({
    'availableBudget' : IDL.Nat,
    'committedBudget' : IDL.Nat,
    'totalBudget' : IDL.Nat,
    'spentBudget' : IDL.Nat,
  });
  const ParticipantBudgetView = IDL.Variant({
    'public' : PublicParticipantBudget,
    'private' : PrivateParticipantBudget,
  });
  const WonPlayer = IDL.Record({
    'playerId' : IDL.Text,
    'team' : IDL.Text,
    'closedAt' : Timestamp,
    'playerName' : IDL.Text,
    'byeWeek' : IDL.Opt(IDL.Nat),
    'nominatedBy' : UserId,
    'position' : IDL.Text,
    'winningBid' : IDL.Nat,
  });
  const ParticipantView = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : UserId,
    'budgetView' : ParticipantBudgetView,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'skipNominationTurn' : IDL.Bool,
    'wonPlayers' : IDL.Vec(WonPlayer),
  });
  const AuctionState = IDL.Variant({
    'Paused' : IDL.Null,
    'Active' : IDL.Null,
    'Waiting' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Room = IDL.Record({
    'id' : RoomId,
    'leagueFormat' : IDL.Opt(IDL.Text),
    'rosterSettings' : IDL.Opt(RosterSettings),
    'participants' : IDL.Vec(UserId),
    'admin' : UserId,
    'nominatorIndex' : IDL.Nat,
    'readyParticipants' : IDL.Vec(UserId),
    'password' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'scoringFormat' : ScoringFormat,
    'startingBudget' : IDL.Nat,
    'teamCount' : IDL.Opt(IDL.Nat),
    'season' : IDL.Nat,
    'nominationTurnPausedAt' : IDL.Opt(Timestamp),
    'playoffTeams' : IDL.Nat,
    'playerFilter' : PlayerFilter,
    'state' : AuctionState,
    'paidParticipants' : IDL.Vec(UserId),
    'settings' : AuctionSettings,
    'gameType' : GameType,
    'isPublic' : IDL.Bool,
    'competitionMode' : CompetitionMode,
    'nominationTurnStartedAt' : Timestamp,
  });
  const ProxyBid = IDL.Record({
    'userId' : UserId,
    'maxBid' : IDL.Nat,
    'nominationId' : NominationId,
  });
  const RoomView = IDL.Record({
    'queuedPlayerId' : IDL.Opt(IDL.Text),
    'participants' : IDL.Vec(ParticipantView),
    'draftedPlayerIds' : IDL.Vec(IDL.Text),
    'currentNominatorName' : IDL.Opt(IDL.Text),
    'currentNominatorId' : IDL.Opt(UserId),
    'room' : Room,
    'nominationTimerSecsRemaining' : IDL.Nat,
    'activeNominations' : IDL.Vec(NominationView),
    'completedNominations' : IDL.Vec(NominationView),
    'myProxyBids' : IDL.Vec(ProxyBid),
  });
  const RoomSummary = IDL.Record({
    'id' : RoomId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'state' : AuctionState,
    'participantCount' : IDL.Nat,
    'maxParticipants' : IDL.Nat,
    'isPublic' : IDL.Bool,
    'adminId' : UserId,
  });
  const StandingsEntry = IDL.Record({
    'displayName' : IDL.Text,
    'participantId' : UserId,
    'totalPoints' : IDL.Float64,
  });
  const LineupSlot = IDL.Record({
    'playerId' : IDL.Opt(IDL.Text),
    'slot' : IDL.Text,
    'position' : IDL.Text,
    'points' : IDL.Float64,
  });
  const LineupBenchEntry = IDL.Record({
    'playerId' : IDL.Text,
    'points' : IDL.Float64,
  });
  const WeeklyLineupView = IDL.Record({
    'total' : IDL.Float64,
    'displayName' : IDL.Text,
    'starters' : IDL.Vec(LineupSlot),
    'week' : IDL.Nat,
    'participantId' : UserId,
    'bench' : IDL.Vec(LineupBenchEntry),
    'roomId' : RoomId,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const WeeklyPlayerStats = IDL.Record({
    'twoPtConversions' : IDL.Nat,
    'receptions' : IDL.Nat,
    'ints' : IDL.Nat,
    'fumblesLost' : IDL.Nat,
    'playerId' : IDL.Text,
    'week' : IDL.Nat,
    'season' : IDL.Nat,
    'passTds' : IDL.Nat,
    'passYds' : IDL.Int,
    'rushTds' : IDL.Nat,
    'rushYds' : IDL.Int,
    'recTds' : IDL.Nat,
    'recYds' : IDL.Int,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    'adminDrainQueueNow' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'backfillFinalizedScores' : IDL.Func([], [IDL.Nat], []),
    'checkIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'clearNominationQueue' : IDL.Func([RoomId], [], []),
    'clearPlayers' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'computeDedupSeasonWeeks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        [],
      ),
    'createRoom' : IDL.Func(
        [
          GameType,
          CompetitionMode,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          AuctionSettings,
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(PlayerFilter),
          IDL.Opt(IDL.Nat),
          IDL.Opt(RosterSettings),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Nat,
          ScoringFormat,
        ],
        [IDL.Variant({ 'ok' : RoomId, 'err' : IDL.Text })],
        [],
      ),
    'deleteRoom' : IDL.Func(
        [RoomId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'editParticipantBudget' : IDL.Func(
        [RoomId, UserId, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'endAuction' : IDL.Func(
        [RoomId, IDL.Opt(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'fetchRssFeeds' : IDL.Func([], [IDL.Text], []),
    'finalizeWeek' : IDL.Func([IDL.Nat, IDL.Nat], [FinalizeResult], []),
    'getADPDataset' : IDL.Func([], [IDL.Opt(ADPDataset)], ['query']),
    'getADPDatasetByType' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ADPDataset)],
        ['query'],
      ),
    'getActiveADPDataset' : IDL.Func([], [IDL.Opt(ADPDataset)], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getBestBallConfig' : IDL.Func(
        [RoomId],
        [IDL.Opt(BestBallConfig)],
        ['query'],
      ),
    'getByeWeeks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getCycleBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getDisplayName' : IDL.Func([UserId], [IDL.Opt(IDL.Text)], ['query']),
    'getFlaggedWeeks' : IDL.Func([], [IDL.Vec(SyncStatusRecord)], []),
    'getGiphyApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getH2HStandings' : IDL.Func(
        [RoomId],
        [IDL.Variant({ 'ok' : IDL.Vec(H2HStandingEntry), 'err' : IDL.Text })],
        ['query'],
      ),
    'getHeartbeatDiagnostics' : IDL.Func(
        [],
        [
          IDL.Record({
            'lastNotificationWorkerError' : IDL.Opt(IDL.Text),
            'lastNotificationWorkerCompletedAt' : IDL.Int,
            'lastNotificationWorkerStartedAt' : IDL.Int,
            'notificationWorkerEntryCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLastRssFetchStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [RoomId, IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getNominationHistory' : IDL.Func(
        [NominationId],
        [IDL.Vec(BidHistoryEvent)],
        ['query'],
      ),
    'getNominationQueue' : IDL.Func([RoomId], [IDL.Opt(IDL.Text)], ['query']),
    'getNominations' : IDL.Func([RoomId], [IDL.Vec(NominationView)], ['query']),
    'getNotificationCounters' : IDL.Func(
        [],
        [
          IDL.Record({
            'expired' : IDL.Nat,
            'sent' : IDL.Nat,
            'queued' : IDL.Nat,
            'processed' : IDL.Nat,
            'failed' : IDL.Nat,
            'retried' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getNotificationQueueSnapshot' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'title' : IDL.Text,
              'userId' : IDL.Text,
              'attempts' : IDL.Nat,
              'ageSeconds' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getOneSignalApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getOneSignalPlayerIds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getPlayerWeeklyPoints' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, ScoringFormat],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getPlayers' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(Player)],
        ['query'],
      ),
    'getPlayersByRoom' : IDL.Func(
        [RoomId, IDL.Text, IDL.Text],
        [IDL.Vec(Player)],
        ['query'],
      ),
    'getPlayersWithADP' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getPlayoffBracket' : IDL.Func(
        [RoomId],
        [IDL.Variant({ 'ok' : PlayoffBracketResult, 'err' : IDL.Text })],
        [],
      ),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'getRoomParticipantPrincipals' : IDL.Func(
        [RoomId],
        [
          IDL.Variant({
            'ok' : IDL.Vec(
              IDL.Record({ 'principal' : IDL.Text, 'displayName' : IDL.Text })
            ),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getRoomState' : IDL.Func(
        [RoomId],
        [IDL.Variant({ 'ok' : RoomView, 'err' : IDL.Text })],
        ['query'],
      ),
    'getRooms' : IDL.Func([], [IDL.Vec(RoomSummary)], []),
    'getRssFeedUrls' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRssRefreshIntervalSecs' : IDL.Func([], [IDL.Nat], ['query']),
    'getStandings' : IDL.Func(
        [RoomId],
        [IDL.Variant({ 'ok' : IDL.Vec(StandingsEntry), 'err' : IDL.Text })],
        ['query'],
      ),
    'getSyncStatusRecords' : IDL.Func(
        [],
        [IDL.Vec(SyncStatusRecord)],
        ['query'],
      ),
    'getUserRooms' : IDL.Func([], [IDL.Vec(RoomSummary)], []),
    'getWeeklyLineup' : IDL.Func(
        [RoomId, UserId, IDL.Nat],
        [IDL.Variant({ 'ok' : WeeklyLineupView, 'err' : IDL.Text })],
        ['query'],
      ),
    'getWeeklyStandings' : IDL.Func(
        [RoomId, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(StandingsEntry), 'err' : IDL.Text })],
        ['query'],
      ),
    'importADPDataset' : IDL.Func(
        [IDL.Vec(AdpEntry), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'importPlayers' : IDL.Func(
        [IDL.Vec(Player)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'joinPrivateRoomByPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : RoomId, 'err' : IDL.Text })],
        [],
      ),
    'joinRoom' : IDL.Func(
        [RoomId, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'leaveRoom' : IDL.Func(
        [RoomId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'listPublicRooms' : IDL.Func([], [IDL.Vec(RoomSummary)], ['query']),
    'nominatePlayer' : IDL.Func(
        [RoomId, IDL.Text],
        [IDL.Variant({ 'ok' : NominationId, 'err' : IDL.Text })],
        [],
      ),
    'pauseAuction' : IDL.Func(
        [RoomId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'placeProxyBid' : IDL.Func(
        [NominationId, RoomId, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'randomizeNominationOrder' : IDL.Func(
        [RoomId],
        [IDL.Variant({ 'ok' : IDL.Vec(UserId), 'err' : IDL.Text })],
        [],
      ),
    'reconcileMembershipIndexes' : IDL.Func([], [], []),
    'recordSyncStatus' : IDL.Func(
        [IDL.Nat, IDL.Nat, SyncStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
        [IDL.Variant({ 'ok' : SyncStatusRecord, 'err' : IDL.Text })],
        [],
      ),
    'recoverAdmin' : IDL.Func([IDL.Text], [Result], []),
    'removeADPDataset' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'removeParticipant' : IDL.Func(
        [RoomId, UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeUserFromRoom' : IDL.Func(
        [RoomId, UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resumeAuction' : IDL.Func(
        [RoomId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendMessage' : IDL.Func(
        [RoomId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'sendTestPush' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'body' : IDL.Text,
              'playerId' : IDL.Text,
              'looksSuccessful' : IDL.Bool,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'setActiveNominationCount' : IDL.Func(
        [RoomId, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setAvatarUrl' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setByeWeeks' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setDisplayName' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setGiphyApiKey' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setNominationOrder' : IDL.Func(
        [RoomId, IDL.Vec(UserId)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setNominationQueue' : IDL.Func(
        [RoomId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setOneSignalApiKey' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setOneSignalPlayerId' : IDL.Func([IDL.Text], [], []),
    'setParticipantPaid' : IDL.Func(
        [RoomId, UserId, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setRecoveryPassword' : IDL.Func([IDL.Text], [Result], []),
    'setRssFeedUrls' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setRssRefreshIntervalSecs' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setSkipNominationTurn' : IDL.Func(
        [RoomId, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'startAuction' : IDL.Func(
        [RoomId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'sweepNominations' : IDL.Func([RoomId], [], []),
    'syncWeeklyStats' : IDL.Func(
        [RoomId, IDL.Nat, IDL.Nat, IDL.Vec(WeeklyPlayerStats)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'toggleMessageReaction' : IDL.Func(
        [RoomId, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'toggleReady' : IDL.Func(
        [RoomId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'transferParticipantIdentity' : IDL.Func(
        [RoomId, UserId, UserId],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateRoomSettings' : IDL.Func(
        [RoomId, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };