/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ADPDataset {
  'lastUpdated' : bigint,
  'importedAt' : bigint,
  'entries' : Array<AdpEntry>,
}
export interface AdpEntry {
  'adp' : number,
  'name' : string,
  'team' : [] | [string],
  'position' : [] | [string],
}
export interface AuctionSettings {
  'minBidIncrement' : bigint,
  'maxActivePicks' : bigint,
  'adpDataset' : string,
  'nomTimerSecs' : bigint,
  'maxParticipants' : bigint,
  'bidTimerSecs' : bigint,
  'maxRosterSize' : [] | [bigint],
}
export type AuctionState = { 'Paused' : null } |
  { 'Active' : null } |
  { 'Waiting' : null } |
  { 'Completed' : null };
export interface BestBallConfig { 'startWeek' : bigint }
export interface BidHistoryEvent {
  'displayName' : string,
  'userId' : UserId,
  'isAutoBid' : [] | [boolean],
  'timestamp' : Timestamp,
  'playerName' : string,
  'amount' : bigint,
  'eventType' : BidHistoryEventType,
}
export type BidHistoryEventType = { 'nominationEnded' : null } |
  { 'leaderChanged' : null } |
  { 'nominationCreated' : null };
export type BracketSlot = { 'WinnerOf' : bigint } |
  { 'Seed' : bigint };
export type BracketSlotState = { 'resolved' : ResolvedContestant } |
  { 'pendingOnDependency' : null } |
  { 'pendingOnSync' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface ChatMessage {
  'id' : bigint,
  'displayName' : string,
  'userId' : UserId,
  'message' : string,
  'timestamp' : Timestamp,
  'reactions' : Array<[string, Array<UserId>]>,
}
export type CompetitionMode = { 'Cumulative' : null } |
  { 'HeadToHead' : null };
export interface CustomScoringSettings {
  'recTdPoints' : number,
  'passYdPoints' : number,
  'intPoints' : number,
  'recYdPoints' : number,
  'twoPtPoints' : number,
  'rushTdPoints' : number,
  'rushYdPoints' : number,
  'fumbleLostPoints' : number,
  'passTdPoints' : number,
  'receptionPoints' : number,
}
export type FinalizeResult = { 'ok' : bigint } |
  { 'err' : string };
export type GameStatus = {
    'resolved' : {
      'winner' : UserId,
      'homeScore' : number,
      'awayScore' : number,
    }
  } |
  { 'pendingOnDependency' : null } |
  { 'pendingOnSync' : null };
export type GameType = { 'BestBall' : null } |
  { 'Guillotine' : null } |
  { 'Auction' : null };
export interface H2HStandingEntry {
  'displayName' : string,
  'gamesPlayed' : bigint,
  'pointsFor' : number,
  'ties' : bigint,
  'wins' : bigint,
  'losses' : bigint,
  'participant' : UserId,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface LineupBenchEntry { 'playerId' : string, 'points' : number }
export interface LineupSlot {
  'playerId' : [] | [string],
  'slot' : string,
  'position' : string,
  'points' : number,
}
export type NominationId = bigint;
export type NominationState = { 'Closed' : null } |
  { 'Active' : null } |
  { 'Expired' : null };
export interface NominationView {
  'id' : NominationId,
  'bidLeader' : [] | [UserId],
  'playerId' : string,
  'team' : string,
  'bidLeaderName' : [] | [string],
  'timerSecsRemaining' : bigint,
  'state' : NominationState,
  'imageUrl' : [] | [string],
  'playerName' : string,
  'nominatedBy' : UserId,
  'currentBid' : bigint,
  'roomId' : RoomId,
  'position' : string,
}
export type ParticipantBudgetView = { 'public' : PublicParticipantBudget } |
  { 'private' : PrivateParticipantBudget };
export interface ParticipantView {
  'displayName' : string,
  'userId' : UserId,
  'budgetView' : ParticipantBudgetView,
  'avatarUrl' : [] | [string],
  'skipNominationTurn' : boolean,
  'wonPlayers' : Array<WonPlayer>,
}
export interface Player {
  'id' : string,
  'adp' : number,
  'yearsExp' : bigint,
  'name' : string,
  'team' : string,
  'byeWeek' : [] | [bigint],
  'position' : string,
  'headshotUrl' : [] | [string],
}
export interface PlayerFilter {
  'filterType' : string,
  'positions' : Array<string>,
}
export interface PlayoffBracketResult {
  'games' : Array<PlayoffGameResult>,
  'champion' : { 'some' : ResolvedContestant } |
    { 'inProgress' : null },
}
export interface PlayoffGame {
  'away' : BracketSlot,
  'home' : BracketSlot,
  'week' : bigint,
}
export interface PlayoffGameResult {
  'status' : GameStatus,
  'away' : BracketSlotState,
  'game' : PlayoffGame,
  'home' : BracketSlotState,
}
export interface PrivateParticipantBudget {
  'availableBudget' : bigint,
  'committedBudget' : bigint,
  'totalBudget' : bigint,
  'spentBudget' : bigint,
}
export interface ProxyBid {
  'userId' : UserId,
  'maxBid' : bigint,
  'nominationId' : NominationId,
}
export interface PublicParticipantBudget {
  'publicAvailableBudget' : bigint,
  'totalBudget' : bigint,
  'spentBudget' : bigint,
}
export interface ResolvedContestant {
  'seed' : bigint,
  'score' : number,
  'participant' : UserId,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface Room {
  'id' : RoomId,
  'leagueFormat' : [] | [string],
  'rosterSettings' : [] | [RosterSettings],
  'participants' : Array<UserId>,
  'admin' : UserId,
  'nominatorIndex' : bigint,
  'readyParticipants' : Array<UserId>,
  'password' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'scoringFormat' : ScoringFormat,
  'startingBudget' : bigint,
  'teamCount' : [] | [bigint],
  'season' : bigint,
  'nominationTurnPausedAt' : [] | [Timestamp],
  'playoffTeams' : bigint,
  'playerFilter' : PlayerFilter,
  'state' : AuctionState,
  'paidParticipants' : Array<UserId>,
  'settings' : AuctionSettings,
  'gameType' : GameType,
  'isPublic' : boolean,
  'competitionMode' : CompetitionMode,
  'nominationTurnStartedAt' : Timestamp,
}
export type RoomId = string;
export interface RoomSummary {
  'id' : RoomId,
  'name' : string,
  'createdAt' : Timestamp,
  'state' : AuctionState,
  'participantCount' : bigint,
  'maxParticipants' : bigint,
  'isPublic' : boolean,
  'adminId' : UserId,
}
export interface RoomView {
  'queuedPlayerId' : [] | [string],
  'participants' : Array<ParticipantView>,
  'draftedPlayerIds' : Array<string>,
  'currentNominatorName' : [] | [string],
  'currentNominatorId' : [] | [UserId],
  'room' : Room,
  'nominationTimerSecsRemaining' : bigint,
  'activeNominations' : Array<NominationView>,
  'completedNominations' : Array<NominationView>,
  'myProxyBids' : Array<ProxyBid>,
}
export interface RosterSettings {
  'qb' : bigint,
  'rb' : bigint,
  'te' : bigint,
  'wr' : bigint,
  'flex' : bigint,
  'superflex' : bigint,
  'superflexPositions' : Array<string>,
  'bench' : bigint,
  'flexPositions' : Array<string>,
}
export type ScoringFormat = { 'ppr' : null } |
  { 'std' : null } |
  { 'halfPpr' : null } |
  { 'custom' : CustomScoringSettings };
export interface StandingsEntry {
  'displayName' : string,
  'participantId' : UserId,
  'totalPoints' : number,
}
export type SyncStatus = { 'finalized' : null } |
  { 'notYetAttempted' : null } |
  { 'partial' : null };
export interface SyncStatusRecord {
  'status' : SyncStatus,
  'lastAttemptedAt' : bigint,
  'week' : bigint,
  'season' : bigint,
  'lastError' : [] | [string],
  'lastSuccessfulAt' : [] | [bigint],
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type UserId = Principal;
export interface UserProfile {
  'displayName' : string,
  'userId' : UserId,
  'avatarUrl' : [] | [string],
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WeeklyLineupView {
  'total' : number,
  'displayName' : string,
  'starters' : Array<LineupSlot>,
  'week' : bigint,
  'participantId' : UserId,
  'bench' : Array<LineupBenchEntry>,
  'roomId' : RoomId,
}
export interface WeeklyPlayerStats {
  'twoPtConversions' : bigint,
  'receptions' : bigint,
  'ints' : bigint,
  'fumblesLost' : bigint,
  'playerId' : string,
  'week' : bigint,
  'season' : bigint,
  'passTds' : bigint,
  'passYds' : bigint,
  'rushTds' : bigint,
  'rushYds' : bigint,
  'recTds' : bigint,
  'recYds' : bigint,
}
export interface WonPlayer {
  'playerId' : string,
  'team' : string,
  'closedAt' : Timestamp,
  'playerName' : string,
  'byeWeek' : [] | [bigint],
  'nominatedBy' : UserId,
  'position' : string,
  'winningBid' : bigint,
}
export interface _SERVICE {
  /**
   * / Admin-only — manually drain the notification queue now.
   * / Thin wrapper around processNotificationQueue; does not modify that function's
   * / signature, auth, or the timer's unguarded call to it.
   * / Returns #ok with the number of notifications processed, or #err "Unauthorized".
   */
  'adminDrainQueueNow' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Host-only recovery: populate the cache for every #finalized week lacking a
   * / cache entry (the post-migration population for pre-existing #synced→
   * / #finalized weeks). Idempotent — only fills missing entries, never
   * / overwrites. Returns the number of scores written.
   */
  'backfillFinalizedScores' : ActorMethod<[], bigint>,
  /**
   * / Query: returns true if the caller is the registered global admin principal.
   * / Used by the frontend to show/hide the Admin section in the sidebar.
   */
  'checkIsAdmin' : ActorMethod<[], boolean>,
  /**
   * / Clear the caller's queued nomination for the given room.
   */
  'clearNominationQueue' : ActorMethod<[RoomId], undefined>,
  /**
   * / Admin-only: clear all players from the players map.
   * / Returns #ok(()) on success or #err if caller is not admin.
   */
  'clearPlayers' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Admin-only: compute the deduplicated set of (season, week) pairs across
   * / all #BestBall rooms' startWeek..FINAL_WEEK ranges. Unions overlapping ranges
   * / across different rooms on the same season. Used by the frontend to know
   * / which weeks exist to sync, and by the daily timer.
   */
  'computeDedupSeasonWeeks' : ActorMethod<[], Array<[bigint, bigint]>>,
  'createRoom' : ActorMethod<
    [
      GameType,
      CompetitionMode,
      bigint,
      string,
      bigint,
      AuctionSettings,
      boolean,
      [] | [string],
      [] | [PlayerFilter],
      [] | [bigint],
      [] | [RosterSettings],
      [] | [bigint],
      [] | [string],
      bigint,
      ScoringFormat,
    ],
    { 'ok' : RoomId } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: delete a room and ALL associated data.
   * / Removes the room from: rooms, participants, nominations, bids, proxyBids,
   * / nominatedByRoom, nominationHistory, and roomMessages.
   * / Returns #ok(()) on success or #err("Room not found") if the room does not exist.
   * /
   * / Best Ball protection: if a BestBallConfig exists for this room, deletion
   * / is refused — the room contains historical Best Ball data — and no removal
   * / logic runs at all.
   */
  'deleteRoom' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Host-only: edit the total budget of a participant.
   * / newBudget must be >= spentBudget (cannot set below already-spent amount).
   */
  'editParticipantBudget' : ActorMethod<
    [RoomId, UserId, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: transition room to Completed.
   * /
   * / `startWeek` is optional and its meaning depends on the room's gameType:
   * /   - #Auction: startWeek must be null. A provided value is rejected with
   * /     #err (never silently ignored).
   * /   - #BestBall: startWeek is required and must satisfy 1 <= startWeek <=
   * /     FINAL_WEEK (17). On success the BestBallConfig { startWeek } is
   * /     written atomically with the completion.
   * /   - #Guillotine: rejected — no lifecycle support in this build.
   * /
   * / Atomicity: all validation happens before any state mutation. If any check
   * / fails, the entire call is rejected and the room is left in its prior
   * / (pre-completion) state — no partial completion, no room stuck #Completed
   * / with a missing/invalid Best Ball config.
   */
  'endAuction' : ActorMethod<
    [RoomId, [] | [bigint]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'execute' : ActorMethod<[string], Result__1>,
  'fetchRssFeeds' : ActorMethod<[], string>,
  /**
   * / Host-only recovery: manually finalize a (season, week) and write its
   * / cache. Only a #partial week may be finalized; a #finalized week is refused
   * / (idempotent). This is a recovery mechanism only — normal operation never
   * / depends on it.
   */
  'finalizeWeek' : ActorMethod<[bigint, bigint], FinalizeResult>,
  /**
   * / Return the current active ADP dataset, or null if none has been imported.
   * / Returns "all" dataset for backwards compatibility.
   */
  'getADPDataset' : ActorMethod<[], [] | [ADPDataset]>,
  /**
   * / Return the ADP dataset for a specific type ("all" or "rookies").
   * / Returns null if no dataset has been imported for that type.
   */
  'getADPDatasetByType' : ActorMethod<[string], [] | [ADPDataset]>,
  /**
   * / Alias for getADPDataset — returns the "all" ADP dataset with lastUpdated timestamp.
   */
  'getActiveADPDataset' : ActorMethod<[], [] | [ADPDataset]>,
  /**
   * / Return a Markdown document describing the backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Any room participant can read the room's BestBallConfig.
   * / Returns null when the room has no Best Ball tracking enabled.
   * / The config carries only `startWeek`; the season always ends at the
   * / module-level `FINAL_WEEK` constant (17).
   */
  'getBestBallConfig' : ActorMethod<[RoomId], [] | [BestBallConfig]>,
  /**
   * / Public query: return the current bye week mapping as an array of
   * / (team, byeWeek) pairs. Not sensitive — bye weeks are public NFL schedule
   * / data. Returns the default 2025 mapping if no admin import has occurred.
   */
  'getByeWeeks' : ActorMethod<[], Array<[string, bigint]>>,
  'getCycleBalance' : ActorMethod<[], bigint>,
  /**
   * / Return the persisted display name for a given user principal, or null if not set.
   * / Public query — callable by any authenticated user.
   */
  'getDisplayName' : ActorMethod<[UserId], [] | [string]>,
  /**
   * / Admin-only: get the flagged (needing-attention) weeks — only the weeks
   * / eligible for a partial sync: the current live week per season (the highest
   * / #partial week, or the first non-finalized week if none) when it is #partial
   * / or #notYetAttempted. Excludes #finalized weeks and #notYetAttempted future
   * / weeks. The frontend runs its existing fetch+parse+submit flow for each
   * / flagged week on admin session load.
   * /
   * / This is an update (not a query) because it also ensures a status record
   * / exists for the live week (creating a #notYetAttempted record when none
   * / exists yet), so newly-created Best Ball rooms are flagged even before the
   * / once-per-day timer runs.
   * /
   * / It also triggers the post-migration cache backfill for pre-existing
   * / #finalized weeks, so those weeks show their correct cached score in
   * / getStandings promptly (on admin session load) rather than waiting up to
   * / 24h for the daily timer. The backfill is idempotent — it only fills missing
   * / entries and never overwrites existing ones.
   */
  'getFlaggedWeeks' : ActorMethod<[], Array<SyncStatusRecord>>,
  /**
   * / Public query — retrieve the Giphy API key.
   * / Callable by any authenticated (non-anonymous) user.
   * / Returns null if no key is stored. Never exposed to anonymous callers.
   */
  'getGiphyApiKey' : ActorMethod<[], [] | [string]>,
  /**
   * / Compute Head-to-Head regular-season standings for a room.
   * /
   * / Rejects with #err if the room is not #BestBall + #HeadToHead, is not found,
   * / or the caller is not a participant. Each team's weekly result is resolved
   * / via the derived pairing table for weeks in startWeek..regularSeasonEnd;
   * / unsynced weeks produce no result (not counted in gamesPlayed), and genuine
   * / ties are allowed with no synthetic tiebreaker. Playoff weeks are out of
   * / scope this phase.
   * /
   * / The result is deterministically ordered: wins descending, pointsFor
   * / descending, then Principal.compare ascending — never map iteration order.
   */
  'getH2HStandings' : ActorMethod<
    [RoomId],
    { 'ok' : Array<H2HStandingEntry> } |
      { 'err' : string }
  >,
  /**
   * / Admin-only query — return heartbeat and notification-worker diagnostics.
   * / Non-admin callers receive all fields zeroed/null (same guard pattern as
   * / getNotificationCounters).
   */
  'getHeartbeatDiagnostics' : ActorMethod<
    [],
    {
      'lastNotificationWorkerError' : [] | [string],
      'lastNotificationWorkerCompletedAt' : bigint,
      'lastNotificationWorkerStartedAt' : bigint,
      'notificationWorkerEntryCount' : bigint,
    }
  >,
  /**
   * / Public query — per-feed outcome of the most recent RSS fetch.
   * / Each tuple is (feedUrl, succeeded). Returns [] for anonymous callers,
   * / consistent with getRssFeedUrls. On cache-hit returns, the previous real
   * / fetch's status is preserved (not overwritten).
   */
  'getLastRssFetchStatus' : ActorMethod<[], Array<[string, boolean]>>,
  /**
   * / Get the most recent `limit` chat messages for a room (newest first).
   */
  'getMessages' : ActorMethod<[RoomId, bigint], Array<ChatMessage>>,
  /**
   * / Return the stored event-based bid history for a nomination.
   * / Events are ordered oldest-first (append order).
   */
  'getNominationHistory' : ActorMethod<[NominationId], Array<BidHistoryEvent>>,
  /**
   * / Return the caller's currently queued player for the given room, or null if none.
   */
  'getNominationQueue' : ActorMethod<[RoomId], [] | [string]>,
  'getNominations' : ActorMethod<[RoomId], Array<NominationView>>,
  /**
   * / Admin-only query — return the six notification lifecycle counters.
   * / Non-admin callers receive all zeros (same guard pattern as getOneSignalPlayerIds).
   */
  'getNotificationCounters' : ActorMethod<
    [],
    {
      'expired' : bigint,
      'sent' : bigint,
      'queued' : bigint,
      'processed' : bigint,
      'failed' : bigint,
      'retried' : bigint,
    }
  >,
  /**
   * / Admin-only query — return a snapshot of the current notification queue.
   * / Each entry exposes id, userId (as Text), title, attempts, and age in seconds.
   * / Non-admin callers receive an empty array (same guard pattern as getOneSignalPlayerIds).
   */
  'getNotificationQueueSnapshot' : ActorMethod<
    [],
    Array<
      {
        'id' : bigint,
        'title' : string,
        'userId' : string,
        'attempts' : bigint,
        'ageSeconds' : bigint,
      }
    >
  >,
  /**
   * / Admin-only query — retrieve the OneSignal REST API key.
   * / The REST API key must NEVER be exposed to non-admin callers.
   * / Returns null for anonymous callers and non-admin callers.
   */
  'getOneSignalApiKey' : ActorMethod<[], [] | [string]>,
  /**
   * / Admin-only query — retrieve all stored principal → OneSignal Player ID mappings.
   * / Returns an empty array for non-admin callers.
   */
  'getOneSignalPlayerIds' : ActorMethod<[], Array<[string, string]>>,
  /**
   * / Public query that computes fantasy points for a stored WeeklyPlayerStats
   * / entry at statsKey(playerId, season, week) under the given ScoringFormat.
   * /
   * / Returns null when no entry exists for that key — keeping null (no data)
   * / and zero (a real zero-point performance) distinguishable. Callable by any
   * / authenticated caller with no room-specific authorization, since it reads
   * / shared NFL stats data.
   */
  'getPlayerWeeklyPoints' : ActorMethod<
    [string, bigint, bigint, ScoringFormat],
    [] | [number]
  >,
  'getPlayers' : ActorMethod<[string, [] | [string]], Array<Player>>,
  /**
   * / Return players eligible under a room's playerFilter, optionally filtered by query text.
   * / Backend enforces the room's position and rookie/veteran filter.
   */
  'getPlayersByRoom' : ActorMethod<[RoomId, string, string], Array<Player>>,
  /**
   * / Return all players enriched with ADP values from the active dataset.
   * / Players with no ADP match retain their existing adp value (0.0 for imported players).
   * / If no dataset is active, returns all players with their original adp values.
   */
  'getPlayersWithADP' : ActorMethod<[], Array<Player>>,
  /**
   * / Derive and resolve the playoff bracket for a #HeadToHead room with
   * / playoffTeams > 0.
   * /
   * / Rejects with #err if the room is not found, is not #BestBall + #HeadToHead,
   * / is a #Cumulative room, has playoffTeams == 0, or the caller is not a
   * / participant. #Cumulative rooms and H2H rooms with playoffTeams == 0 each
   * / get a clear, distinct error message.
   * /
   * / Seeding comes from getH2HStandings' existing deterministic ordering (wins →
   * / pointsFor → Principal.compare), restricted to the top playoffTeams entries.
   * / Bracket seed numbers are 1-based: `#Seed n` resolves to the participant
   * / occupying seed `n` in that ordering, i.e. standings array index `n - 1`.
   */
  'getPlayoffBracket' : ActorMethod<
    [RoomId],
    { 'ok' : PlayoffBracketResult } |
      { 'err' : string }
  >,
  /**
   * / Return the caller's global profile (principal, displayName, avatarUrl).
   */
  'getProfile' : ActorMethod<[], UserProfile>,
  /**
   * / Admin-only query — return each joined participant's principal ID (as Text)
   * / paired with their display name for the given room, so the admin can see and
   * / copy the principal IDs of all joined participants. Works on rooms in any
   * / state (Waiting, Active, Paused, Completed) since the admin needs to inspect
   * / principals in a live Active room. Rejects non-admin callers with #err.
   */
  'getRoomParticipantPrincipals' : ActorMethod<
    [RoomId],
    { 'ok' : Array<{ 'principal' : string, 'displayName' : string }> } |
      { 'err' : string }
  >,
  'getRoomState' : ActorMethod<
    [RoomId],
    { 'ok' : RoomView } |
      { 'err' : string }
  >,
  /**
   * / Return ALL rooms (public and private) as RoomSummary list.
   * / Access-gated: only a global admin (isGlobalAdmin) receives the full list;
   * / any other caller receives an empty array so private-room metadata is never
   * / leaked to non-admins. AdminPanel relies on this for full visibility.
   */
  'getRooms' : ActorMethod<[], Array<RoomSummary>>,
  /**
   * / Public query — retrieve the configured RSS feed URLs.
   * / Returns the default list if nothing has been configured yet.
   */
  'getRssFeedUrls' : ActorMethod<[], Array<string>>,
  /**
   * / Public query — retrieve the configured RSS refresh interval in seconds.
   */
  'getRssRefreshIntervalSecs' : ActorMethod<[], bigint>,
  /**
   * / Compute Cumulative Best Ball standings for a room.
   * /
   * / Each participant's cumulative score is the sum of their optimal Best Ball
   * / weekly score across every applicable week from BestBallConfig.startWeek
   * / through FINAL_WEEK (17, inclusive), computed via the Phase 3
   * / calculator — no second scoring/lineup algorithm. Unsynced weeks contribute
   * / 0 points and do not fail the calculation; missing individual player stats
   * / contribute 0 while the player stays owned/benched.
   * /
   * / The result is deterministically ordered: descending by cumulative points,
   * / with equal scores broken by the stable participant identifier (ascending),
   * / so ordering never depends on map iteration order.
   * /
   * / Access: the caller must be a participant of the room. Non-Best-Ball rooms
   * / are rejected.
   */
  'getStandings' : ActorMethod<
    [RoomId],
    { 'ok' : Array<StandingsEntry> } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: get all sync status records (for the admin status view).
   * / Each record carries its status and relevant timestamp (lastSuccessfulAt
   * / if synced, lastAttemptedAt + lastError if failed, lastAttemptedAt if
   * / empty/pending).
   */
  'getSyncStatusRecords' : ActorMethod<[], Array<SyncStatusRecord>>,
  /**
   * / Return all rooms the caller has joined as RoomSummary list.
   * /
   * / Self-healing (Fix 1): this is now an UPDATE func (not query) so it can
   * / repair the userRooms index when it has drifted. It does NOT trust the
   * / userRooms index alone — it iterates every room and uses
   * / AuctionLib.isParticipant (which checks room.participants, the
   * / authoritative source) to decide membership. If a room the caller is a
   * / participant of is missing from their userRooms index, it is added; if the
   * / index contains a room the caller is no longer a participant of, it is
   * / removed. The participant count is sourced from room.participants.size()
   * / (Fix 4), and the inner participants map is reconciled first.
   */
  'getUserRooms' : ActorMethod<[], Array<RoomSummary>>,
  /**
   * / Retrieve one participant's optimal Best Ball lineup for one week.
   * /
   * / Identifies the room, participant, and week using the existing identifier
   * / types (RoomId = Text, UserId = Principal, week = Nat). Returns the Phase 3
   * / calculator result unchanged (starters, bench, total) plus participant/team
   * / identity and the week.
   * /
   * / An unsynced week returns an empty lineup with total 0 — not an error — per
   * / the Phase 3 semantics. Missing individual player stats contribute 0 points
   * / while the player remains owned (and may appear on the bench).
   * /
   * / Access: the caller must be a participant of the room. Non-Best-Ball rooms
   * / are rejected.
   */
  'getWeeklyLineup' : ActorMethod<
    [RoomId, UserId, bigint],
    { 'ok' : WeeklyLineupView } |
      { 'err' : string }
  >,
  /**
   * / Compute single-week Best Ball standings for a room.
   * /
   * / Each participant's score for the requested `week` is their optimal Best
   * / Ball weekly score for that single week, computed via the Phase 3
   * / calculator — no second scoring/lineup algorithm. An unsynced week
   * / contributes 0 points for each participant and does not fail the
   * / calculation (consistent with how getStandings treats unsynced weeks within
   * / its sum); missing individual player stats contribute 0 while the player
   * / stays owned/benched.
   * /
   * / The result is deterministically ordered exactly like getStandings:
   * / descending by points, with equal scores broken by the stable participant
   * / identifier (ascending), so ordering never depends on map iteration order.
   * /
   * / Access: the caller must be a participant of the room. Non-Best-Ball rooms
   * / are rejected. The requested week must fall within the room's configured
   * / BestBallConfig range (startWeek..FINAL_WEEK inclusive); a week outside that
   * / range is rejected with #err.
   */
  'getWeeklyStandings' : ActorMethod<
    [RoomId, bigint],
    { 'ok' : Array<StandingsEntry> } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: import an ADP dataset, keyed by datasetType ("all" or "rookies").
   * / entries: array of AdpEntry (name + adp required, position/team optional).
   * / Validates: max 2000 entries, non-numeric adp values rejected, duplicates ignored.
   */
  'importADPDataset' : ActorMethod<
    [Array<AdpEntry>, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: batch import players from the Sleeper API.
   * / The frontend fetches from https://api.sleeper.app/v1/players/nfl and sends
   * / filtered, mapped batches here. NO backend HTTP outcall is made.
   * / Returns the total number of players now stored.
   * / Admin is assigned on first profile registration (setDisplayName), not here.
   */
  'importPlayers' : ActorMethod<
    [Array<Player>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Join a private room by password only (no room name/code field).
   * / Matches private rooms (isPublic == false) server-side by password and
   * / returns only the matched RoomId on success. On failure (no private room
   * / matches the password) returns a single generic error — it does NOT
   * / distinguish "no room exists with this password" from any other failure
   * / reason, so this endpoint cannot be used to enumerate private rooms or
   * / probe for valid passwords one at a time beyond what the existing
   * / single-password-field UX already allows.
   */
  'joinPrivateRoomByPassword' : ActorMethod<
    [string],
    { 'ok' : RoomId } |
      { 'err' : string }
  >,
  'joinRoom' : ActorMethod<
    [RoomId, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'leaveRoom' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Return only public rooms (isPublic == true) as RoomSummary list for the lobby.
   */
  'listPublicRooms' : ActorMethod<[], Array<RoomSummary>>,
  'nominatePlayer' : ActorMethod<
    [RoomId, string],
    { 'ok' : NominationId } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: transition room from Active → Paused (freezes all timers)
   */
  'pauseAuction' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Place a proxy (max) bid — the only bidding entry point.
   * / maxBid is private; only visible bid is public.
   * / Immediately resolves against existing proxy bids to set correct currentBid and leader.
   * / Visible bid starts at $1 when first bid placed, auto-increments by $1 when outbid.
   * / If caller is already the leader and increases max, visible bid does NOT change (no timer reset).
   */
  'placeProxyBid' : ActorMethod<
    [NominationId, RoomId, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Host-only: randomly shuffle the nomination order (participants array) in the room.
   * / Uses a Fisher-Yates shuffle seeded from Time.now().
   * / Only allowed when the auction is in Waiting or Paused state.
   */
  'randomizeNominationOrder' : ActorMethod<
    [RoomId],
    { 'ok' : Array<UserId> } |
      { 'err' : string }
  >,
  /**
   * / One-time repair entry point called from the actor's postupgrade hook
   * / (Fix 2). Rebuilds the entire userRooms index from room.participants and
   * / reconciles every room's inner participants map. Public so main.mo can
   * / invoke it; not intended for end-user calls.
   */
  'reconcileMembershipIndexes' : ActorMethod<[], undefined>,
  /**
   * / Admin-only: record/update the sync status for a (season, week).
   * /
   * / The atomic duplicate-sync guard lives here, checked and set within the
   * / same call: if the (season, week) is already #finalized, the submission is
   * / rejected with #err and cannot reprocess or replace the terminal state.
   * / #partial and #notYetAttempted are retry-eligible and may be overwritten.
   * /
   * / This is the new adjacent method for status recording — it does NOT change
   * / syncWeeklyStats's public signature or manual-flow behavior.
   */
  'recordSyncStatus' : ActorMethod<
    [bigint, bigint, SyncStatus, [] | [string], [] | [bigint]],
    { 'ok' : SyncStatusRecord } |
      { 'err' : string }
  >,
  /**
   * / Anyone: recover admin access by proving knowledge of the recovery password.
   * / On success, reassigns adminPrincipalStore to the caller (replacing whoever
   * / was previously stored) and clears the caller's recoveryAttempts entry.
   */
  'recoverAdmin' : ActorMethod<[string], Result>,
  /**
   * / Admin-only: remove the ADP dataset for a specific type ("all" or "rookies").
   */
  'removeADPDataset' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Host-only: remove a participant from the room.
   * / Only allowed when the auction is in Waiting or Paused state.
   * / Cannot remove the room admin.
   */
  'removeParticipant' : ActorMethod<
    [RoomId, UserId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: remove another user from the room
   */
  'removeUserFromRoom' : ActorMethod<
    [RoomId, UserId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: transition room from Paused → Active (resumes all timers)
   */
  'resumeAuction' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Send a chat message to a room.
   * / Caller must be a participant in the room.
   */
  'sendMessage' : ActorMethod<
    [RoomId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin-only diagnostic: send a single test push notification to the caller's
   * / own stored OneSignal player ID, bypassing the notification queue entirely.
   * / Mirrors the real outcall in processNotificationQueue exactly (same endpoint,
   * / same payload shape, same app_id, same auth header) but returns the raw
   * / OneSignal response so the admin can diagnose key/permission issues directly.
   * / Does NOT read from or write to notificationQueue.
   */
  'sendTestPush' : ActorMethod<
    [],
    {
        'ok' : {
          'body' : string,
          'playerId' : string,
          'looksSuccessful' : boolean,
        }
      } |
      { 'err' : string }
  >,
  /**
   * / Host-only: set the number of simultaneous active nominations (maxActivePicks).
   * / count must be between 1 and the number of participants in the room.
   */
  'setActiveNominationCount' : ActorMethod<
    [RoomId, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Store the avatar URL for the caller's profile.
   * / Passing an empty string clears the avatar (sets avatarUrl = null).
   */
  'setAvatarUrl' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Admin-only: replace the entire bye week mapping atomically.
   * / Validates that each team abbreviation is non-empty and each bye week is
   * / between 1 and 18 (NFL regular season weeks). Returns an error if any
   * / entry is invalid. On success, also re-applies bye weeks to already-imported
   * / players so the change takes effect immediately: each player's byeWeek is
   * / updated based on their team using the new mapping; players whose team is
   * / not in the mapping get byeWeek = null.
   */
  'setByeWeeks' : ActorMethod<
    [Array<[string, bigint]>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Set (or update) the caller's display name globally.
   * / Also propagates the name change to all rooms the caller has joined.
   * / If no admin has been set yet, the first user to call this becomes the admin.
   */
  'setDisplayName' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: store the Giphy API key.
   * / If the key is empty after trimming, stores null (removes any existing key).
   * / Returns #ok with a confirmation message, or #err if the caller is not admin.
   */
  'setGiphyApiKey' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Host-only: set the nomination order for the room.
   * / orderedUsers must contain exactly the principals currently in the room.
   * / Only allowed when the auction is in Waiting or Paused state.
   */
  'setNominationOrder' : ActorMethod<
    [RoomId, Array<UserId>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Store a pre-selected nomination for the caller in this room.
   * / Fires automatically when the caller's nomination turn starts (via sweepExpiredNominations).
   */
  'setNominationQueue' : ActorMethod<
    [RoomId, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: store the OneSignal REST API key.
   * / If the key is empty after trimming, stores null (removes any existing key).
   * / Returns #ok with a confirmation message, or #err if the caller is not admin.
   */
  'setOneSignalApiKey' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Any authenticated user: store their OneSignal Player ID tied to their principal.
   * / If id is empty after trimming, removes the entry.
   */
  'setOneSignalPlayerId' : ActorMethod<[string], undefined>,
  /**
   * / Host-only: toggle a participant's paid status in a room's
   * / paidParticipants list. Callable only when caller == room.admin. Adds
   * / targetUserId idempotently when paid=true (only if not already present),
   * / removes it when paid=false. Mirrors toggleReady's pattern. Paid status is
   * / informational only — does not affect starting the auction.
   */
  'setParticipantPaid' : ActorMethod<
    [RoomId, UserId, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: set (or overwrite) the recovery password.
   * / Rejects secrets shorter than 16 characters with #err. Non-admins get
   * / #err "Not authorized". On success hashes newSecret and stores it in
   * / recoveryPasswordHash, overwriting any previous value.
   */
  'setRecoveryPassword' : ActorMethod<[string], Result>,
  /**
   * / Admin-only: set the list of RSS feed URLs to aggregate.
   * / Clears the RSS cache so the next fetch uses the new URLs.
   */
  'setRssFeedUrls' : ActorMethod<
    [Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: set the RSS cache refresh interval in seconds.
   * / Minimum is 60 seconds. Clears the cache so the new interval takes effect.
   */
  'setRssRefreshIntervalSecs' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Set the caller's skipNominationTurn flag for a room. When true,
   * / advanceNominatorIndex skips the caller's nomination turn (a standing
   * / toggle until turned off again). A participant can only set their own
   * / flag. Mirrors toggleReady's pattern for room/participant lookup and
   * / notification draining.
   */
  'setSkipNominationTurn' : ActorMethod<
    [RoomId, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: transition room from Waiting → Active
   */
  'startAuction' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Public update — triggers sweepExpiredNominations for a room.
   * / Frontend calls this to drive timer resolution without polling.
   */
  'sweepNominations' : ActorMethod<[RoomId], undefined>,
  /**
   * / Endpoint that receives a typed batch of raw weekly player stats and
   * / upserts them into weeklyPlayerStats. The backend does NOT fetch or parse
   * / anything itself — the frontend fetches from Sleeper and sends the typed
   * / batch here.
   * /
   * / Authorization:
   * /   - the global admin is authorized unconditionally (unchanged), OR
   * /   - a participant of the room identified by `roomId`, provided
   * /     `room.season == season` (the season param must match the room's
   * /     actual season).
   * / If `roomId` does not resolve to a real room, or the caller is not a
   * / participant of it, the call is rejected with a clear #err.
   * /
   * / For each entry in the batch:
   * /   - verifies entry.season == season and entry.week == week; mismatched
   * /     entries are skipped (counted in a diagnostic) without failing the call
   * /   - upserts valid entries keyed by statsKey(entry.playerId, season, week),
   * /     so re-running an already-synced week cleanly overwrites (no duplicates)
   * /
   * / Returns #ok with the count of entries successfully stored.
   */
  'syncWeeklyStats' : ActorMethod<
    [RoomId, bigint, bigint, Array<WeeklyPlayerStats>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'toggleMessageReaction' : ActorMethod<
    [RoomId, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Toggle the caller's ready status in a room's readyParticipants list.
   * / If the caller is NOT in readyParticipants → add them (no duplicates).
   * / If the caller IS in readyParticipants → remove them.
   * / Returns #err if the room is not found or the caller is not a participant.
   */
  'toggleReady' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Admin-only: reassign a participant's slot from one principal to another.
   * /
   * / Transfers ALL participant-specific state from oldPrincipal to newPrincipal
   * / so the user keeps their roster, budget, bid history, nomination position,
   * / proxy bids, and nomination queue entry under the new principal. Works on
   * / Active and Paused rooms (does NOT gate on room.state) — this is the recovery
   * / path for a user who is locked out of their original principal.
   * /
   * / Updates ALL THREE membership stores atomically:
   * /   (1) room.participants — replaces oldPrincipal with newPrincipal at the
   * /       SAME array index to preserve nomination order position.
   * /   (2) participants inner map — moves the Participant record from the old
   * /       key to the new key, preserving budget, spent, committed, wonPlayers,
   * /       displayName, and all other fields.
   * /   (3) userRooms — removes roomId from oldPrincipal's list and adds it to
   * /       newPrincipal's list.
   * /
   * / Also transfers participant-specific data keyed by principal:
   * /   - bids (per nomination List<Bid>) — rewrites Bid.userId for the user's bids
   * /   - proxyBids (per nomination Map<UserId, ProxyBid>) — moves the entry and
   * /     rewrites ProxyBid.userId
   * /   - nominationHistory (per nomination List<BidHistoryEvent>) — rewrites
   * /     BidHistoryEvent.userId for the user's events
   * /   - nominationQueue (keyed by "roomId|userId.toText()") — moves the entry
   * /   - nominations (Nomination.nominatedBy / Nomination.bidLeader) — rewrites
   * /     any reference to oldPrincipal so the user's active nominations and bid
   * /     leadership are preserved under the new principal
   * /
   * / Guard: admin-only — same global admin guard pattern as deleteRoom /
   * / getOneSignalPlayerIds (hardcoded principal OR adminPrincipalStore.get("admin")).
   */
  'transferParticipantIdentity' : ActorMethod<
    [RoomId, UserId, UserId],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  /**
   * / Admin-only: update room timer settings and max active picks.
   * / Allowed in Waiting state, Active (with no active nominations), or Paused.
   */
  'updateRoomSettings' : ActorMethod<
    [RoomId, bigint, bigint, [] | [bigint], string],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];