/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ADPDataset {
  'lastUpdated' : bigint,
  'importedAt' : bigint,
  'entries' : Array<AdpEntry>,
}
export interface AdpEntry {
  'adp' : number,
  'name' : string,
  'team' : [] | [string],
  'position' : [] | [string],
}
export interface AuctionSettings {
  'minBidIncrement' : bigint,
  'maxActivePicks' : bigint,
  'adpDataset' : string,
  'nomTimerSecs' : bigint,
  'maxParticipants' : bigint,
  'bidTimerSecs' : bigint,
  'maxRosterSize' : [] | [bigint],
}
export type AuctionState = { 'Paused' : null } |
  { 'Active' : null } |
  { 'Waiting' : null } |
  { 'Completed' : null };
export interface BestBallConfig { 'startWeek' : bigint, 'endWeek' : bigint }
export interface BidHistoryEvent {
  'displayName' : string,
  'userId' : UserId,
  'isAutoBid' : [] | [boolean],
  'timestamp' : Timestamp,
  'playerName' : string,
  'amount' : bigint,
  'eventType' : BidHistoryEventType,
}
export type BidHistoryEventType = { 'nominationEnded' : null } |
  { 'leaderChanged' : null } |
  { 'nominationCreated' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface ChatMessage {
  'id' : bigint,
  'displayName' : string,
  'userId' : UserId,
  'message' : string,
  'timestamp' : Timestamp,
  'reactions' : Array<[string, Array<UserId>]>,
}
export interface CustomScoringSettings {
  'recTdPoints' : number,
  'passYdPoints' : number,
  'intPoints' : number,
  'recYdPoints' : number,
  'twoPtPoints' : number,
  'rushTdPoints' : number,
  'rushYdPoints' : number,
  'fumbleLostPoints' : number,
  'passTdPoints' : number,
  'receptionPoints' : number,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type NominationId = bigint;
export type NominationState = { 'Closed' : null } |
  { 'Active' : null } |
  { 'Expired' : null };
export interface NominationView {
  'id' : NominationId,
  'bidLeader' : [] | [UserId],
  'playerId' : string,
  'team' : string,
  'bidLeaderName' : [] | [string],
  'timerSecsRemaining' : bigint,
  'state' : NominationState,
  'imageUrl' : [] | [string],
  'playerName' : string,
  'nominatedBy' : UserId,
  'currentBid' : bigint,
  'roomId' : RoomId,
  'position' : string,
}
export type ParticipantBudgetView = { 'public' : PublicParticipantBudget } |
  { 'private' : PrivateParticipantBudget };
export interface ParticipantView {
  'displayName' : string,
  'userId' : UserId,
  'budgetView' : ParticipantBudgetView,
  'avatarUrl' : [] | [string],
  'skipNominationTurn' : boolean,
  'wonPlayers' : Array<WonPlayer>,
}
export interface Player {
  'id' : string,
  'adp' : number,
  'yearsExp' : bigint,
  'name' : string,
  'team' : string,
  'byeWeek' : [] | [bigint],
  'position' : string,
  'headshotUrl' : [] | [string],
}
export interface PlayerFilter {
  'filterType' : string,
  'positions' : Array<string>,
}
export interface PrivateParticipantBudget {
  'availableBudget' : bigint,
  'committedBudget' : bigint,
  'totalBudget' : bigint,
  'spentBudget' : bigint,
}
export interface ProxyBid {
  'userId' : UserId,
  'maxBid' : bigint,
  'nominationId' : NominationId,
}
export interface PublicParticipantBudget {
  'publicAvailableBudget' : bigint,
  'totalBudget' : bigint,
  'spentBudget' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface Room {
  'id' : RoomId,
  'leagueFormat' : [] | [string],
  'rosterSettings' : [] | [RosterSettings],
  'participants' : Array<UserId>,
  'admin' : UserId,
  'nominatorIndex' : bigint,
  'readyParticipants' : Array<UserId>,
  'password' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'scoringFormat' : ScoringFormat,
  'startingBudget' : bigint,
  'teamCount' : [] | [bigint],
  'season' : bigint,
  'nominationTurnPausedAt' : [] | [Timestamp],
  'playerFilter' : PlayerFilter,
  'state' : AuctionState,
  'paidParticipants' : Array<UserId>,
  'settings' : AuctionSettings,
  'isPublic' : boolean,
  'nominationTurnStartedAt' : Timestamp,
}
export type RoomId = string;
export interface RoomSummary {
  'id' : RoomId,
  'name' : string,
  'createdAt' : Timestamp,
  'state' : AuctionState,
  'participantCount' : bigint,
  'maxParticipants' : bigint,
  'isPublic' : boolean,
  'adminId' : UserId,
}
export interface RoomView {
  'queuedPlayerId' : [] | [string],
  'participants' : Array<ParticipantView>,
  'draftedPlayerIds' : Array<string>,
  'currentNominatorName' : [] | [string],
  'currentNominatorId' : [] | [UserId],
  'room' : Room,
  'nominationTimerSecsRemaining' : bigint,
  'activeNominations' : Array<NominationView>,
  'completedNominations' : Array<NominationView>,
  'myProxyBids' : Array<ProxyBid>,
}
export interface RosterSettings {
  'qb' : bigint,
  'rb' : bigint,
  'te' : bigint,
  'wr' : bigint,
  'flex' : bigint,
  'superflex' : bigint,
  'superflexPositions' : Array<string>,
  'bench' : bigint,
  'flexPositions' : Array<string>,
}
export type ScoringFormat = { 'ppr' : null } |
  { 'std' : null } |
  { 'halfPpr' : null } |
  { 'custom' : CustomScoringSettings };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type UserId = Principal;
export interface UserProfile {
  'displayName' : string,
  'userId' : UserId,
  'avatarUrl' : [] | [string],
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WeeklyPlayerStats {
  'twoPtConversions' : bigint,
  'receptions' : bigint,
  'ints' : bigint,
  'fumblesLost' : bigint,
  'playerId' : string,
  'week' : bigint,
  'season' : bigint,
  'passTds' : bigint,
  'passYds' : bigint,
  'rushTds' : bigint,
  'rushYds' : bigint,
  'recTds' : bigint,
  'recYds' : bigint,
}
export interface WonPlayer {
  'playerId' : string,
  'team' : string,
  'closedAt' : Timestamp,
  'playerName' : string,
  'byeWeek' : [] | [bigint],
  'nominatedBy' : UserId,
  'position' : string,
  'winningBid' : bigint,
}
export interface _SERVICE {
  'adminDrainQueueNow' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'checkIsAdmin' : ActorMethod<[], boolean>,
  'clearNominationQueue' : ActorMethod<[RoomId], undefined>,
  'clearPlayers' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'createRoom' : ActorMethod<
    [
      string,
      bigint,
      AuctionSettings,
      boolean,
      [] | [string],
      [] | [PlayerFilter],
      [] | [bigint],
      [] | [RosterSettings],
      [] | [bigint],
      [] | [string],
      bigint,
      ScoringFormat,
    ],
    { 'ok' : RoomId } |
      { 'err' : string }
  >,
  'deleteRoom' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  'editParticipantBudget' : ActorMethod<
    [RoomId, UserId, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'endAuction' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  'execute' : ActorMethod<[string], Result__1>,
  'fetchRssFeeds' : ActorMethod<[], string>,
  'getADPDataset' : ActorMethod<[], [] | [ADPDataset]>,
  'getADPDatasetByType' : ActorMethod<[string], [] | [ADPDataset]>,
  'getActiveADPDataset' : ActorMethod<[], [] | [ADPDataset]>,
  'getBestBallConfig' : ActorMethod<[RoomId], [] | [BestBallConfig]>,
  'getByeWeeks' : ActorMethod<[], Array<[string, bigint]>>,
  'getCycleBalance' : ActorMethod<[], bigint>,
  'getDisplayName' : ActorMethod<[UserId], [] | [string]>,
  'getGiphyApiKey' : ActorMethod<[], [] | [string]>,
  'getHeartbeatDiagnostics' : ActorMethod<
    [],
    {
      'lastNotificationWorkerError' : [] | [string],
      'lastNotificationWorkerCompletedAt' : bigint,
      'lastNotificationWorkerStartedAt' : bigint,
      'notificationWorkerEntryCount' : bigint,
    }
  >,
  'getLastRssFetchStatus' : ActorMethod<[], Array<[string, boolean]>>,
  'getMessages' : ActorMethod<[RoomId, bigint], Array<ChatMessage>>,
  'getNominationHistory' : ActorMethod<[NominationId], Array<BidHistoryEvent>>,
  'getNominationQueue' : ActorMethod<[RoomId], [] | [string]>,
  'getNominations' : ActorMethod<[RoomId], Array<NominationView>>,
  'getNotificationCounters' : ActorMethod<
    [],
    {
      'expired' : bigint,
      'sent' : bigint,
      'queued' : bigint,
      'processed' : bigint,
      'failed' : bigint,
      'retried' : bigint,
    }
  >,
  'getNotificationQueueSnapshot' : ActorMethod<
    [],
    Array<
      {
        'id' : bigint,
        'title' : string,
        'userId' : string,
        'attempts' : bigint,
        'ageSeconds' : bigint,
      }
    >
  >,
  'getOneSignalApiKey' : ActorMethod<[], [] | [string]>,
  'getOneSignalPlayerIds' : ActorMethod<[], Array<[string, string]>>,
  'getPlayerWeeklyPoints' : ActorMethod<
    [string, bigint, bigint, ScoringFormat],
    [] | [number]
  >,
  'getPlayers' : ActorMethod<[string, [] | [string]], Array<Player>>,
  'getPlayersByRoom' : ActorMethod<[RoomId, string, string], Array<Player>>,
  'getPlayersWithADP' : ActorMethod<[], Array<Player>>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getRoomParticipantPrincipals' : ActorMethod<
    [RoomId],
    { 'ok' : Array<{ 'principal' : string, 'displayName' : string }> } |
      { 'err' : string }
  >,
  'getRoomState' : ActorMethod<
    [RoomId],
    { 'ok' : RoomView } |
      { 'err' : string }
  >,
  'getRooms' : ActorMethod<[], Array<RoomSummary>>,
  'getRssFeedUrls' : ActorMethod<[], Array<string>>,
  'getRssRefreshIntervalSecs' : ActorMethod<[], bigint>,
  'getUserRooms' : ActorMethod<[], Array<RoomSummary>>,
  'importADPDataset' : ActorMethod<
    [Array<AdpEntry>, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'importPlayers' : ActorMethod<
    [Array<Player>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'joinPrivateRoomByPassword' : ActorMethod<
    [string],
    { 'ok' : RoomId } |
      { 'err' : string }
  >,
  'joinRoom' : ActorMethod<
    [RoomId, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'leaveRoom' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  'listPublicRooms' : ActorMethod<[], Array<RoomSummary>>,
  'nominatePlayer' : ActorMethod<
    [RoomId, string],
    { 'ok' : NominationId } |
      { 'err' : string }
  >,
  'pauseAuction' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  'placeProxyBid' : ActorMethod<
    [NominationId, RoomId, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'randomizeNominationOrder' : ActorMethod<
    [RoomId],
    { 'ok' : Array<UserId> } |
      { 'err' : string }
  >,
  'reconcileMembershipIndexes' : ActorMethod<[], undefined>,
  'recoverAdmin' : ActorMethod<[string], Result>,
  'removeADPDataset' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'removeParticipant' : ActorMethod<
    [RoomId, UserId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeUserFromRoom' : ActorMethod<
    [RoomId, UserId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resumeAuction' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  'schema' : ActorMethod<[], string>,
  'sendMessage' : ActorMethod<
    [RoomId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendTestPush' : ActorMethod<
    [],
    {
        'ok' : {
          'body' : string,
          'playerId' : string,
          'looksSuccessful' : boolean,
        }
      } |
      { 'err' : string }
  >,
  'setActiveNominationCount' : ActorMethod<
    [RoomId, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setAvatarUrl' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'setBestBallConfig' : ActorMethod<[RoomId, bigint, bigint], Result>,
  'setByeWeeks' : ActorMethod<
    [Array<[string, bigint]>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setDisplayName' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setGiphyApiKey' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setNominationOrder' : ActorMethod<
    [RoomId, Array<UserId>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setNominationQueue' : ActorMethod<
    [RoomId, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setOneSignalApiKey' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setOneSignalPlayerId' : ActorMethod<[string], undefined>,
  'setParticipantPaid' : ActorMethod<
    [RoomId, UserId, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setRecoveryPassword' : ActorMethod<[string], Result>,
  'setRssFeedUrls' : ActorMethod<
    [Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setRssRefreshIntervalSecs' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSkipNominationTurn' : ActorMethod<
    [RoomId, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'startAuction' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  'sweepNominations' : ActorMethod<[RoomId], undefined>,
  'syncWeeklyStats' : ActorMethod<
    [bigint, bigint, Array<WeeklyPlayerStats>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'toggleMessageReaction' : ActorMethod<
    [RoomId, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'toggleReady' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  'transferParticipantIdentity' : ActorMethod<
    [RoomId, UserId, UserId],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateRoomSettings' : ActorMethod<
    [RoomId, bigint, bigint, [] | [bigint], string],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];